In [1]:
import torch

# hstack 在行上拼接

Stack tensors in sequence horizontally (column wise).

# hsplit 在行上拆分
Splits input, a tensor with one or more dimensions, into multiple tensors horizontally according to indices_or_sections. Each split is a view of input.

In [3]:
# a,b都是水平1行竖直3列，h拼接后还是1行，长度翻倍
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a

tensor([1, 2, 3])

In [4]:
b

tensor([4, 5, 6])

In [7]:
c = torch.hstack((a, b))
c

tensor([1, 2, 3, 4, 5, 6])

In [8]:
torch.hsplit(c, 2) # 分为2份

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [11]:
# d,e都是是水平3行竖直1列，h拼接后就变为3行2列了
d = torch.tensor([
                [1],
                [2],
                [3]
            ])
e = torch.tensor([
                [4],
                [5],
                [6]
            ])
d

tensor([[1],
        [2],
        [3]])

In [12]:
e

tensor([[4],
        [5],
        [6]])

In [14]:
f = torch.hstack((d, e))
f

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [15]:
torch.hsplit(f, 2)

(tensor([[1],
         [2],
         [3]]),
 tensor([[4],
         [5],
         [6]]))