In [1]:
import torch

In [2]:
# 来自https://github.com/NagatoYuki0943/d2l-zh/blob/master/chapter_preliminaries/ndarray.ipynb

## 广播机制
:label:`subsec_broadcasting`

在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。
在某些情况下，[**即使形状不同，我们仍然可以通过调用
*广播机制*（broadcasting mechanism）来执行按元素操作**]。
这种机制的工作方式如下：

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

在大多数情况下，我们将沿着数组中长度为1的轴进行广播，如下例子：


In [3]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。
我们将两个矩阵*广播*为一个更大的$3\times2$矩阵，如下所示：矩阵`a`将复制列，
矩阵`b`将复制行，然后再按元素相加。


In [4]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 有广播机制不需要repeat

In [8]:
x = torch.randn(1, 10, 8)
y = torch.randn(10, 1, 8)
x.shape, y.shape

(torch.Size([1, 10, 8]), torch.Size([10, 1, 8]))

In [9]:
(x + y).shape

torch.Size([10, 10, 8])

In [11]:
torch.all((x + y) == (x.repeat(10, 1, 1) + y.repeat(1, 10, 1)))

tensor(True)