In [1]:
import torch

# 加减乘除

In [2]:
a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[1, 1], [1, 1]])

## add 加法

In [3]:
a + b

tensor([[2, 2],
        [3, 3]])

In [4]:
torch.add(a, b)

tensor([[2, 2],
        [3, 3]])

## sub subtract 减法

In [5]:
a - b

tensor([[0, 0],
        [1, 1]])

In [6]:
torch.sub(a, b)

tensor([[0, 0],
        [1, 1]])

In [7]:
torch.subtract(a, b)

tensor([[0, 0],
        [1, 1]])

## mul multiply 乘法

In [8]:
a * b

tensor([[1, 1],
        [2, 2]])

In [9]:
torch.multiply(a, b)

tensor([[1, 1],
        [2, 2]])

In [10]:
torch.mul(a, b)

tensor([[1, 1],
        [2, 2]])

## divide 除法

In [11]:
a / b

tensor([[1., 1.],
        [2., 2.]])

In [12]:
torch.div(a, b)

tensor([[1., 1.],
        [2., 2.]])

In [13]:
torch.divide(a, b)

tensor([[1., 1.],
        [2., 2.]])

# n次方

## tensor ** 2 / tensor.square(n) 2次方

In [14]:
g = torch.tensor([[0, 1], [2, 3]])

In [15]:
g.square()

tensor([[0, 1],
        [4, 9]])

In [16]:
torch.square(g)

tensor([[0, 1],
        [4, 9]])

In [17]:
torch.pow(g, 2)

tensor([[0, 1],
        [4, 9]])

## tensor ** n / tensor.pow(n) 多次方

In [18]:
g = torch.tensor([[0, 1], [2, 3]])

In [19]:
g**3

tensor([[ 0,  1],
        [ 8, 27]])

In [20]:
g.pow(3)

tensor([[ 0,  1],
        [ 8, 27]])

## torch.exp(tensor) / tensor.exp() e的tensor次方

In [21]:
g = torch.tensor([[0, 1], [2, 3]])

In [22]:
torch.exp(g)

tensor([[ 1.0000,  2.7183],
        [ 7.3891, 20.0855]])

In [23]:
g.exp()

tensor([[ 1.0000,  2.7183],
        [ 7.3891, 20.0855]])

## torch.exp2(tensor) / tensor.exp2() 2的tensor次方

In [24]:
torch.exp2(g)

tensor([[1., 2.],
        [4., 8.]])

In [25]:
g.exp2()

tensor([[1., 2.],
        [4., 8.]])

# 开方

## torch.sqrt(tensor) / tensor.sqrt() 开方

In [26]:
torch.sqrt(torch.tensor([1, 2, 4, 9]))

tensor([1.0000, 1.4142, 2.0000, 3.0000])

In [27]:
torch.tensor([1, 2, 4, 9]).sqrt()

tensor([1.0000, 1.4142, 2.0000, 3.0000])

## torch.rsqrt(tensor) / tensor.rsqrt() 开方的倒数

In [28]:
torch.rsqrt(torch.tensor([1, 2, 4, 9]))

tensor([1.0000, 0.7071, 0.5000, 0.3333])

In [29]:
1 / torch.rsqrt(torch.tensor([1, 2, 4, 9]))

tensor([1.0000, 1.4142, 2.0000, 3.0000])

In [30]:
torch.tensor([1, 2, 4, 9]).rsqrt()

tensor([1.0000, 0.7071, 0.5000, 0.3333])

In [31]:
1 / torch.tensor([1, 2, 4, 9]).rsqrt()

tensor([1.0000, 1.4142, 2.0000, 3.0000])

# torch.log(tensor) / tensor.log() ln(tensor)

In [32]:
torch.log(g.exp())

tensor([[0., 1.],
        [2., 3.]])

In [33]:
g.exp().log()

tensor([[0., 1.],
        [2., 3.]])

# torch.log2(tensor) / tensor.log2() log_2(tensor)

In [34]:
torch.log2(g.exp2())

tensor([[0., 1.],
        [2., 3.]])

In [35]:
g.exp2().log2()

tensor([[0., 1.],
        [2., 3.]])

# torch.log10(tensor) / tensor.log10() log_10(tensor)

In [36]:
i = torch.tensor([10, 100, 1000])

In [37]:
torch.log10(i)

tensor([1., 2., 3.])

In [38]:
i.log10()

tensor([1., 2., 3.])

# floor() ceil() round() trunc() frac()
- floor() 向下取整

- ceil() 向上取整

- round() 四舍五入

- trunc() 整数部分

- frac()  小数部分

In [39]:
pi = torch.tensor(torch.pi)
pi

tensor(3.1416)

In [40]:
pi.floor(), pi.ceil(), pi.round(), pi.trunc(), pi.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(3.), tensor(0.1416))

# torch.sum(tensor, dim=int/[int], keepdim=True)

In [94]:
j = torch.arange(2 * 3 * 4).reshape(2, 3, 4) - 2 * 3 * 4 / 2
j, j.shape

(tensor([[[-12., -11., -10.,  -9.],
          [ -8.,  -7.,  -6.,  -5.],
          [ -4.,  -3.,  -2.,  -1.]],
 
         [[  0.,   1.,   2.,   3.],
          [  4.,   5.,   6.,   7.],
          [  8.,   9.,  10.,  11.]]]),
 torch.Size([2, 3, 4]))

In [95]:
torch.sum(j)

tensor(-12.)

In [96]:
j.sum()

tensor(-12.)

## dim 相当于在哪个维度计算,就去除这个维度,使用 keepdim=True 会将这个维度调整为1,方便广播机制

In [97]:
j.sum(dim=0), j.sum(dim=0).shape
# dim=0 消失了

(tensor([[-12., -10.,  -8.,  -6.],
         [ -4.,  -2.,   0.,   2.],
         [  4.,   6.,   8.,  10.]]),
 torch.Size([3, 4]))

In [98]:
j.sum(dim=0, keepdim=True), j.sum(dim=0, keepdim=True).shape
# dim=0 调整为1

(tensor([[[-12., -10.,  -8.,  -6.],
          [ -4.,  -2.,   0.,   2.],
          [  4.,   6.,   8.,  10.]]]),
 torch.Size([1, 3, 4]))

In [99]:
j.sum(dim=1), j.sum(dim=1).shape
# dim=1 消失了

(tensor([[-24., -21., -18., -15.],
         [ 12.,  15.,  18.,  21.]]),
 torch.Size([2, 4]))

In [100]:
j.sum(dim=1, keepdim=True), j.sum(dim=1, keepdim=True).shape
# dim=1 调整为1

(tensor([[[-24., -21., -18., -15.]],
 
         [[ 12.,  15.,  18.,  21.]]]),
 torch.Size([2, 1, 4]))

In [101]:
j.sum(dim=2), j.sum(dim=2).shape
# dim=2 消失了

(tensor([[-42., -26., -10.],
         [  6.,  22.,  38.]]),
 torch.Size([2, 3]))

In [102]:
j.sum(dim=2, keepdim=True), j.sum(dim=2, keepdim=True).shape
# dim=2 调整为1

(tensor([[[-42.],
          [-26.],
          [-10.]],
 
         [[  6.],
          [ 22.],
          [ 38.]]]),
 torch.Size([2, 3, 1]))

In [103]:
j.sum(dim=[1, 2]), j.sum(dim=[1, 2]).shape
# dim=1,2 消失了

(tensor([-78.,  66.]), torch.Size([2]))

In [104]:
j.sum(dim=[1, 2], keepdim=True), j.sum(dim=[1, 2], keepdim=True).shape
# dim=1,2 调整为1

(tensor([[[-78.]],
 
         [[ 66.]]]),
 torch.Size([2, 1, 1]))

# torch.abs(tensor) 绝对值

In [107]:
j

tensor([[[-12., -11., -10.,  -9.],
         [ -8.,  -7.,  -6.,  -5.],
         [ -4.,  -3.,  -2.,  -1.]],

        [[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]]])

In [108]:
torch.abs(j)

tensor([[[12., 11., 10.,  9.],
         [ 8.,  7.,  6.,  5.],
         [ 4.,  3.,  2.,  1.]],

        [[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])

In [109]:
j.abs()

tensor([[[12., 11., 10.,  9.],
         [ 8.,  7.,  6.,  5.],
         [ 4.,  3.,  2.,  1.]],

        [[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])

# torch.neg(tensor) 相反数

In [110]:
j

tensor([[[-12., -11., -10.,  -9.],
         [ -8.,  -7.,  -6.,  -5.],
         [ -4.,  -3.,  -2.,  -1.]],

        [[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]]])

In [111]:
torch.neg(j)

tensor([[[ 12.,  11.,  10.,   9.],
         [  8.,   7.,   6.,   5.],
         [  4.,   3.,   2.,   1.]],

        [[ -0.,  -1.,  -2.,  -3.],
         [ -4.,  -5.,  -6.,  -7.],
         [ -8.,  -9., -10., -11.]]])

In [112]:
j.neg()

tensor([[[ 12.,  11.,  10.,   9.],
         [  8.,   7.,   6.,   5.],
         [  4.,   3.,   2.,   1.]],

        [[ -0.,  -1.,  -2.,  -3.],
         [ -4.,  -5.,  -6.,  -7.],
         [ -8.,  -9., -10., -11.]]])

# dim=[dim1, dim2...] 多个维度的计算方式

In [113]:
k = torch.arange(20, dtype=torch.float32).reshape(5, 4)
k

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。

In [114]:
k.sum(dim=[0, 1])

tensor(190.)

In [115]:
k.sum()

tensor(190.)

# torch.cumsum(tensor)

如果我们想沿[**某个轴计算`A`元素的累积总和**]，
比如`axis=0`（按行计算），可以调用`cumsum`函数。
此函数不会沿任何轴降低输入张量的维度。


In [116]:
k

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [117]:
torch.cumsum(k, dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [118]:
k.cumsum(dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [119]:
k.cumsum(dim=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

# 点积（Dot Product）torch.dot(tensor1, tensor2)

我们已经学习了按元素操作、求和及平均值。
另一个最基本的操作之一是点积。
给定两个向量$\mathbf{x},\mathbf{y}\in\mathbb{R}^d$，
它们的*点积*（dot product）$\mathbf{x}^\top\mathbf{y}$
（或$\langle\mathbf{x},\mathbf{y}\rangle$）
是相同位置的按元素乘积的和：$\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$。

[~~点积是相同位置的按元素乘积的和~~]


In [120]:
l = torch.arange(4, dtype=torch.float32)
m = torch.ones(4, dtype=torch.float32)
l, m, torch.dot(l, m)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

注意，(**我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积**)：


In [121]:
torch.sum(l * m)

tensor(6.)

点积在很多场合都很有用。
例如，给定一组由向量$\mathbf{x} \in \mathbb{R}^d$表示的值，
和一组由$\mathbf{w} \in \mathbb{R}^d$表示的权重。
$\mathbf{x}$中的值根据权重$\mathbf{w}$的加权和，
可以表示为点积$\mathbf{x}^\top \mathbf{w}$。
当权重为非负数且和为1（即$\left(\sum_{i=1}^{d}{w_i}=1\right)$）时，
点积表示*加权平均*（weighted average）。
将两个向量规范化得到单位长度后，点积表示它们夹角的余弦。
本节后面的内容将正式介绍*长度*（length）的概念。

# 矩阵-向量积 torch.mv(tensor1, tensor2)

现在我们知道如何计算点积，可以开始理解*矩阵-向量积*（matrix-vector product）。
回顾分别在 :eqref:`eq_matrix_def`和 :eqref:`eq_vec_def`中定义的矩阵$\mathbf{A} \in \mathbb{R}^{m \times n}$和向量$\mathbf{x} \in \mathbb{R}^n$。
让我们将矩阵$\mathbf{A}$用它的行向量表示：

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix},$$

其中每个$\mathbf{a}^\top_{i} \in \mathbb{R}^n$都是行向量，表示矩阵的第$i$行。
[**矩阵向量积$\mathbf{A}\mathbf{x}$是一个长度为$m$的列向量，
其第$i$个元素是点积$\mathbf{a}^\top_i \mathbf{x}$**]：

$$
\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}.
$$

我们可以把一个矩阵$\mathbf{A} \in \mathbb{R}^{m \times n}$乘法看作一个从$\mathbb{R}^{n}$到$\mathbb{R}^{m}$向量的转换。
这些转换是非常有用的，例如可以用方阵的乘法来表示旋转。
后续章节将讲到，我们也可以使用矩阵-向量积来描述在给定前一层的值时，
求解神经网络每一层所需的复杂计算。

在代码中使用张量表示矩阵-向量积，我们使用`mv`函数。
当我们为矩阵`A`和向量`x`调用`torch.mv(A, x)`时，会执行矩阵-向量积。
注意，`A`的列维数（沿轴1的长度）必须与`x`的维数（其长度）相同。



In [122]:
k

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [123]:
l

tensor([0., 1., 2., 3.])

In [124]:
torch.mv(k, l)

tensor([ 14.,  38.,  62.,  86., 110.])