In [1]:
import numpy as np
import torch

# numpy

In [10]:
x = np.ones((2, 2))
x

array([[1., 1.],
       [1., 1.]])

In [11]:
y = x
y

array([[1., 1.],
       [1., 1.]])

## += -= *= /= 会同时影响多个变量

In [12]:
x += 2
x, y

(array([[3., 3.],
        [3., 3.]]),
 array([[3., 3.],
        [3., 3.]]))

## = 只会影响单一变量

In [13]:
x = x + 3
x, y

(array([[6., 6.],
        [6., 6.]]),
 array([[3., 3.],
        [3., 3.]]))

# pytorch

In [14]:
x = torch.ones((2, 2))
x

tensor([[1., 1.],
        [1., 1.]])

In [15]:
y = x
y

tensor([[1., 1.],
        [1., 1.]])

## += -= *= /= 会同时影响多个变量

In [16]:
x += 2
x, y

(tensor([[3., 3.],
         [3., 3.]]),
 tensor([[3., 3.],
         [3., 3.]]))

## = 只会影响单一变量

In [17]:
x = x + 3
x, y

(tensor([[6., 6.],
         [6., 6.]]),
 tensor([[3., 3.],
         [3., 3.]]))