In [1]:
import torch

# 复数

## python 复数

In [2]:
2 + 3j

(2+3j)

In [3]:
a = 2. + 3.j
a

(2+3j)

In [4]:
torch.tensor(2 + 3j)

tensor(2.+3.j)

In [5]:
torch.tensor(2 + 3j).dtype

torch.complex64

In [6]:
torch.tensor(2. + 3.j).dtype

torch.complex64

## 对称数据输入

In [7]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2.]))

tensor([1.+2.j])

In [8]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2.])).dtype

torch.complex64

In [9]:
torch.complex(real=torch.tensor([1., 2.]), imag=torch.tensor([2., 3.]))

tensor([1.+2.j, 2.+3.j])

In [10]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([[2., 3.], [4., 5.]]))

tensor([[1.+2.j, 2.+3.j],
        [3.+4.j, 4.+5.j]])

## 不对称数据输入

In [11]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2., 3.]))

tensor([1.+2.j, 1.+3.j])

In [12]:
torch.complex(real=torch.tensor([1., 2.]), imag=torch.tensor([3.]))

tensor([1.+3.j, 2.+3.j])

In [13]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([[2., 3.]]))

tensor([[1.+2.j, 2.+3.j],
        [3.+2.j, 4.+3.j]])

In [14]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([2., 3.]))

tensor([[1.+2.j, 2.+3.j],
        [3.+2.j, 4.+3.j]])

## 随机数生成

In [18]:
x = torch.randn(4, dtype=torch.cfloat)
x

tensor([ 0.6077-0.4879j,  1.0221-1.0493j, -0.8733-0.2128j, -1.0224-2.1385j])

# view_as_real

In [21]:
y = torch.view_as_real(x)
y

tensor([[ 0.6077, -0.4879],
        [ 1.0221, -1.0493],
        [-0.8733, -0.2128],
        [-1.0224, -2.1385]])

# view_as_complex

In [23]:
torch.view_as_complex(y)

tensor([ 0.6077-0.4879j,  1.0221-1.0493j, -0.8733-0.2128j, -1.0224-2.1385j])