In [34]:
import torch

# 复数

## python 复数

In [35]:
2 + 3j

(2+3j)

In [36]:
a = 2. + 3.j
a

(2+3j)

In [37]:
torch.tensor(2 + 3j)

tensor(2.+3.j)

In [38]:
torch.tensor(2 + 3j).dtype

torch.complex64

In [39]:
torch.tensor(2. + 3.j).dtype

torch.complex64

## 对称数据输入

In [40]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2.]))

tensor([1.+2.j])

In [41]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2.])).dtype

torch.complex64

In [42]:
torch.complex(real=torch.tensor([1., 2.]), imag=torch.tensor([2., 3.]))

tensor([1.+2.j, 2.+3.j])

In [43]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([[2., 3.], [4., 5.]]))

tensor([[1.+2.j, 2.+3.j],
        [3.+4.j, 4.+5.j]])

## 不对称数据输入

In [44]:
torch.complex(real=torch.tensor([1.]), imag=torch.tensor([2., 3.]))

tensor([1.+2.j, 1.+3.j])

In [45]:
torch.complex(real=torch.tensor([1., 2.]), imag=torch.tensor([3.]))

tensor([1.+3.j, 2.+3.j])

In [46]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([[2., 3.]]))

tensor([[1.+2.j, 2.+3.j],
        [3.+2.j, 4.+3.j]])

In [47]:
torch.complex(real=torch.tensor([[1., 2.], [3., 4.]]), imag=torch.tensor([2., 3.]))

tensor([[1.+2.j, 2.+3.j],
        [3.+2.j, 4.+3.j]])