In [1]:
import torch

# mul 点乘

In [2]:
a = torch.randn(1, 1)
b = torch.randn(2, 2)
a

tensor([[-0.2963]])

In [3]:
b

tensor([[-0.8786,  0.7609],
        [-0.1736, -0.2425]])

## 标量 * 矩阵

In [4]:
a * b

tensor([[ 0.2603, -0.2255],
        [ 0.0514,  0.0718]])

In [5]:
torch.mul(a, b)

tensor([[ 0.2603, -0.2255],
        [ 0.0514,  0.0718]])

In [6]:
(a * b) == (torch.mul(a, b))

tensor([[True, True],
        [True, True]])

## 矩阵 * 矩阵 两个矩阵最后维度必须相同
- [a, b, c, d] * [d]
- [a, b, c, d] * [c, d]
- [a, b, c, d] * [b, c, d]
- [a, b, c, d] * [a, b, c, d]

In [7]:
c = torch.randn(3, 3)
c

tensor([[-3.1796, -1.1761, -0.7587],
        [-0.5531,  0.6916, -0.2434],
        [-0.4435, -0.4965,  0.6445]])

In [8]:
# 形状不同会报错
b * c

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
d1 = torch.rand(2, 2)
b, d1

(tensor([[ 0.1496, -0.7133],
         [-1.9682,  1.4093]]),
 tensor([[0.7109, 0.6913],
         [0.8957, 0.5487]]))

In [9]:
b * d1

NameError: name 'd1' is not defined

In [10]:
d2 = torch.rand(1, 2)
b, d2

(tensor([[-0.8786,  0.7609],
         [-0.1736, -0.2425]]),
 tensor([[0.9488, 0.8121]]))

In [11]:
b * d2

tensor([[-0.8336,  0.6179],
        [-0.1647, -0.1969]])

In [12]:
torch.randn(2, 3, 4, 2) * torch.randn(2)

tensor([[[[-0.0892,  0.5081],
          [-0.1433,  0.0385],
          [-0.0113,  0.3708],
          [ 0.0156, -0.7048]],

         [[ 0.1201,  0.7061],
          [-0.0286, -0.1620],
          [-0.1054, -0.2291],
          [ 0.0032, -0.5202]],

         [[ 0.0849, -0.3838],
          [ 0.1062, -0.0165],
          [ 0.0610,  0.0648],
          [-0.0204,  0.1861]]],


        [[[ 0.1325, -0.3418],
          [ 0.0690, -0.2968],
          [ 0.1211,  0.2116],
          [ 0.0526, -0.1258]],

         [[-0.1101, -0.0206],
          [ 0.0042,  0.4626],
          [ 0.0779, -0.2276],
          [ 0.0837,  0.8178]],

         [[-0.1277, -0.2887],
          [ 0.0359, -0.4684],
          [-0.0077, -0.1699],
          [-0.0116, -0.3737]]]])

In [13]:
torch.randn(2, 3, 4, 2) * torch.randn(4, 2)

tensor([[[[ 2.2767e-01, -8.1327e-01],
          [ 9.7653e-01,  2.9009e-01],
          [-3.5966e-02,  1.2159e-01],
          [-1.4898e+00,  2.8849e-01]],

         [[-3.0857e-01, -8.2426e-02],
          [-8.4507e-01, -1.3885e-01],
          [-1.2540e+00,  2.0613e-01],
          [-6.0491e-01,  3.4560e-01]],

         [[ 1.6174e-03,  1.8972e-01],
          [-4.9924e-01,  6.4335e-01],
          [ 2.6545e-01, -9.9797e-02],
          [ 1.0857e-01,  3.0009e-01]]],


        [[[ 2.7117e-01, -3.9384e-01],
          [ 2.2024e+00, -8.8031e-01],
          [-2.7595e+00, -2.5020e-01],
          [-2.9664e-01, -4.3429e-01]],

         [[ 4.9283e-01, -6.8939e-02],
          [-3.9167e-01,  1.2038e-01],
          [-1.4954e+00, -1.9473e-01],
          [ 5.0572e-01,  1.0265e-01]],

         [[ 9.0815e-02,  6.1186e-01],
          [ 2.1220e-01, -6.1752e-01],
          [ 5.5772e-01, -5.5403e-02],
          [ 1.5112e+00,  4.3217e-01]]]])

In [14]:
torch.randn(2, 3, 4, 2) * torch.randn(3, 4, 2)

tensor([[[[ 1.4829e+00, -7.3283e-01],
          [ 6.0635e-02,  7.8544e-02],
          [-1.2303e+00, -1.0101e+00],
          [ 2.3576e-01, -2.5661e-01]],

         [[ 9.8992e-01,  4.4730e-01],
          [-5.7897e-02,  3.4322e-01],
          [-1.8643e+00, -1.0339e-01],
          [ 9.4683e-01,  1.1617e+00]],

         [[-1.3864e+00, -3.4396e-01],
          [-3.8650e-01, -1.2220e+00],
          [ 1.5031e+00, -1.5863e-01],
          [ 5.5264e-01, -2.8424e-02]]],


        [[[-4.4568e-01, -8.0195e-01],
          [-7.8017e-02, -9.1841e-01],
          [ 1.1731e+00, -1.0222e+00],
          [-3.2944e-01,  7.3448e-01]],

         [[ 7.6622e-02,  9.4132e-02],
          [-7.5638e-02,  2.0964e+00],
          [ 5.1916e-01, -9.8815e-01],
          [-4.6681e-05,  2.3203e-01]],

         [[ 1.1972e-02,  6.2937e-01],
          [ 1.0584e+00,  1.2202e+00],
          [ 1.4191e+00, -2.7747e-02],
          [-8.9762e-01, -1.4711e-03]]]])

# matmul / @ 矩阵相乘

## 二维矩阵相乘

In [15]:
e = torch.randn(2, 3)
f = torch.randn(3, 2)
e, f

(tensor([[-0.2757, -0.6909,  0.3226],
         [ 0.9161,  0.9417, -0.5857]]),
 tensor([[ 0.1427, -0.3676],
         [ 1.1920,  0.9164],
         [-2.1507, -1.0666]]))

In [16]:
e @ f

tensor([[-1.5566, -0.8758],
        [ 2.5129,  1.1509]])

In [17]:
torch.matmul(e, f)

tensor([[-1.5566, -0.8758],
        [ 2.5129,  1.1509]])

In [18]:
(e @ f) == (torch.matmul(e, f))

tensor([[True, True],
        [True, True]])

## torch.mm(mat1, mat2) 只适用于二维矩阵相乘,不推荐

In [19]:
torch.mm(e, f)

tensor([[-1.5566, -0.8758],
        [ 2.5129,  1.1509]])

## torch.bmm(mat1, mat2) 只适用于3维矩阵相乘,前面代表batch

In [20]:
e_ = torch.randn(2, 3, 2)
f_ = torch.randn(2, 2, 3)
e_, f_

(tensor([[[ 0.2996, -0.1439],
          [-0.4523, -1.6505],
          [ 0.1724, -0.2343]],
 
         [[ 0.3030,  0.6366],
          [-1.3315,  0.2194],
          [ 0.6152,  0.1006]]]),
 tensor([[[-3.1084, -0.9774, -1.5193],
          [ 1.4561, -2.0154, -1.6304]],
 
         [[-1.3349,  1.1676,  0.0124],
          [ 0.1161,  1.4588,  1.6030]]]))

In [21]:
torch.bmm(e_, f_)

tensor([[[-1.1407e+00, -2.8412e-03, -2.2056e-01],
         [-9.9739e-01,  3.7684e+00,  3.3782e+00],
         [-8.7700e-01,  3.0371e-01,  1.2011e-01]],

        [[-3.3050e-01,  1.2824e+00,  1.0243e+00],
         [ 1.8030e+00, -1.2345e+00,  3.3530e-01],
         [-8.0952e-01,  8.6503e-01,  1.6890e-01]]])

## 高维矩阵相乘,后两个维度相乘,前面形状必须相同

In [25]:
g = torch.randn(1, 2, 3, 4)
h = torch.randn(1, 2, 4, 5)

In [26]:
g @ h

tensor([[[[ 1.9695, -1.3831, -1.5139,  1.6532, -0.0141],
          [ 0.3755, -1.2980, -1.1030,  1.0264,  0.8245],
          [ 0.3957,  1.1723,  1.0948, -0.2563, -1.0181]],

         [[ 0.0308, -1.7732, -1.9777, -2.5227,  1.5138],
          [ 0.3405, -0.5997, -1.4621, -2.2375,  0.7511],
          [ 0.8005, -0.6414, -2.2731, -3.4168,  1.3186]]]])

In [27]:
torch.matmul(g, h)

tensor([[[[ 1.9695, -1.3831, -1.5139,  1.6532, -0.0141],
          [ 0.3755, -1.2980, -1.1030,  1.0264,  0.8245],
          [ 0.3957,  1.1723,  1.0948, -0.2563, -1.0181]],

         [[ 0.0308, -1.7732, -1.9777, -2.5227,  1.5138],
          [ 0.3405, -0.5997, -1.4621, -2.2375,  0.7511],
          [ 0.8005, -0.6414, -2.2731, -3.4168,  1.3186]]]])

In [30]:
i = torch.randn(1, 2, 5, 2)

In [32]:
g @ h @ i

tensor([[[[-0.0754, -2.2628],
          [-0.1287,  0.4948],
          [ 0.6659, -1.3126]],

         [[ 7.8100,  3.5696],
          [ 5.6024,  1.8027],
          [ 8.8032,  2.5171]]]])

## torch.matmul(mat1, mat2) torch.matmul只支持2个矩阵相乘

In [34]:
torch.matmul(g, h, i)

TypeError: matmul(): argument 'other' (position 2) must be Tensor, not list

In [35]:
j = torch.randn(2, 4, 5)

## 前面维度不相同不能相乘

In [36]:
g * j

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 3