In [1]:
import torch

# mul 点乘

In [24]:
a = torch.randn(1, 1)
b = torch.randn(2, 2)
a, b

(tensor([[0.1238]]),
 tensor([[-1.3162,  0.5022],
         [ 0.9084,  0.6821]]))

## 标量 * 矩阵

In [25]:
a * b

tensor([[-0.1630,  0.0622],
        [ 0.1125,  0.0845]])

In [26]:
torch.mul(a, b)

tensor([[-0.1630,  0.0622],
        [ 0.1125,  0.0845]])

In [27]:
(a * b) == (torch.mul(a, b))

tensor([[True, True],
        [True, True]])

## 矩阵 * 矩阵 两个矩阵最后维度必须相同
- [a, b, c, d] * [d]
- [a, b, c, d] * [c, d]
- [a, b, c, d] * [b, c, d]
- [a, b, c, d] * [a, b, c, d]

In [28]:
c = torch.randn(3, 3)
c

tensor([[-0.6384, -0.7982,  1.7158],
        [-1.6066, -1.4074,  0.4552],
        [-0.6892,  0.9224,  0.9375]])

In [29]:
# 形状不同会报错
b * c

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [30]:
d = torch.rand(2, 2)
b.shape, d.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [31]:
b * d

tensor([[-1.0495,  0.0319],
        [ 0.5384,  0.5587]])

In [32]:
d = torch.rand(1, 2)
b.shape, d.shape

(torch.Size([2, 2]), torch.Size([1, 2]))

In [33]:
b * d

tensor([[-0.1177,  0.4545],
        [ 0.0812,  0.6174]])

In [38]:
(torch.randn(1, 2, 3, 4) * torch.randn(4)).shape

torch.Size([1, 2, 3, 4])

In [39]:
(torch.randn(1, 2, 3, 4) * torch.randn(3, 4)).shape

torch.Size([1, 2, 3, 4])

In [40]:
(torch.randn(1, 2, 3, 4) * torch.randn(2, 3, 4)).shape

torch.Size([1, 2, 3, 4])

In [41]:
(torch.randn(1, 2, 3, 4) * torch.randn(1, 2, 3, 4)).shape

torch.Size([1, 2, 3, 4])

# 矩阵相乘

## @ / matmul

In [50]:
e = torch.randn(2, 3)
f = torch.randn(3, 2)
e.shape, f.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [51]:
e @ f

tensor([[ 0.5843,  0.1751],
        [-0.6987, -0.0777]])

In [52]:
torch.matmul(e, f)

tensor([[ 0.5843,  0.1751],
        [-0.6987, -0.0777]])

In [53]:
(e @ f) == (torch.matmul(e, f))

tensor([[True, True],
        [True, True]])

## torch.mm(mat1, mat2) 只适用于二维矩阵相乘,不推荐

In [54]:
torch.mm(e, f)

tensor([[ 0.5843,  0.1751],
        [-0.6987, -0.0777]])

## torch.bmm(mat1, mat2) 只适用于3维矩阵相乘,前面代表batch

In [55]:
e = torch.randn(2, 3, 2)
f = torch.randn(2, 2, 3)
e.shape, f.shape

(torch.Size([2, 3, 2]), torch.Size([2, 2, 3]))

In [56]:
torch.bmm(e, f).shape

torch.Size([2, 3, 3])

In [57]:
torch.all(e @ f == torch.bmm(e, f))

tensor(True)

## 高维矩阵相乘,后两个维度相乘,前面形状必须相同

In [59]:
g = torch.randn(1, 2, 3, 4)
h = torch.randn(1, 2, 4, 5)

In [60]:
(g @ h).shape

torch.Size([1, 2, 3, 5])

In [61]:
torch.matmul(g, h).shape

torch.Size([1, 2, 3, 5])

In [62]:
torch.all((g @ h) == torch.matmul(g, h))

tensor(True)

In [63]:
i = torch.randn(1, 2, 5, 2)

In [64]:
g @ h @ i

tensor([[[[ 9.4267, -4.5995],
          [ 6.5426,  3.6352],
          [-2.1945,  0.4195]],

         [[ 0.9272,  0.7541],
          [-4.0069, -0.5874],
          [ 1.3944, -1.3363]]]])

## 前面维度不相同不能相乘

In [66]:
j = torch.randn(2, 3, 4)
k = torch.randn(3, 3, 4)

In [67]:
j @ k

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0