In [1]:
import torch

In [2]:
x = torch.ones(2, 2, 3)
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

# 矩阵+标量

In [3]:
x + 1

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [4]:
x + torch.tensor(1)

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [5]:
x + torch.tensor([1])

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

# 矩阵+向量，从维度右侧匹配

In [9]:
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [10]:
x + torch.tensor([1, 2])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [11]:
# 匹配最后维度
x + torch.tensor([1, 2, 3])

tensor([[[2., 3., 4.],
         [2., 3., 4.]],

        [[2., 3., 4.],
         [2., 3., 4.]]])

In [12]:
# 匹配最后2个维度
x + torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[[2., 3., 4.],
         [5., 6., 7.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])

In [14]:
# 匹配3个维度
x + torch.tensor([[[1, 2, 3], [4, 5, 6]]])

tensor([[[2., 3., 4.],
         [5., 6., 7.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])

In [26]:
# 匹配3个维度
x + torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

tensor([[[ 2.,  3.,  4.],
         [ 5.,  6.,  7.]],

        [[ 8.,  9., 10.],
         [11., 12., 13.]]])

# 矩阵*标量

In [15]:
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [16]:
x * 2

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [17]:
x * torch.tensor(2)

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [18]:
x * torch.tensor([2])

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

# 矩阵*向量，从维度右侧匹配

In [19]:
x

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [21]:
x * torch.tensor([2, 3])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [22]:
# 匹配最后维度
x * torch.tensor([2, 3, 4])

tensor([[[2., 3., 4.],
         [2., 3., 4.]],

        [[2., 3., 4.],
         [2., 3., 4.]]])

In [23]:
# 匹配最后2个维度
x * torch.tensor([[2, 3, 4], [5, 6, 7]])

tensor([[[2., 3., 4.],
         [5., 6., 7.]],

        [[2., 3., 4.],
         [5., 6., 7.]]])

In [25]:
# 匹配3个维度
x + torch.tensor([[[2, 3, 4], [5, 6, 7]]])

tensor([[[3., 4., 5.],
         [6., 7., 8.]],

        [[3., 4., 5.],
         [6., 7., 8.]]])

In [27]:
# 匹配3个维度
x + torch.tensor([[[2, 3, 4], [5, 6, 7]], [[8, 9, 10], [11, 12, 13]]])

tensor([[[ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 9., 10., 11.],
         [12., 13., 14.]]])