In [1]:
import torch

In [2]:
a = torch.arange(-2., 5, 1)
b = torch.arange(-3., 4, 1)
c = torch.stack((a, b), dim=0)
c

tensor([[-2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-3., -2., -1.,  0.,  1.,  2.,  3.]])

# tensor.norm(p=1, dim=n, keepdim=False)  l1求l1范数

每个值的绝对值之和(开一次方等于不开方)

$$
∥w∥_1
$$

In [3]:
# 默认展平操作
c.norm(p=1)

tensor(25.)

In [4]:
# 保持维度不变
c.norm(p=1, keepdim=True)

tensor([[25.]])

In [5]:
# 指定dim才在指定dim操作
c.norm(p=1, dim=-1)

tensor([13., 12.])

In [6]:
c.norm(p=1, dim=-1, keepdim=True)

tensor([[13.],
        [12.]])

In [7]:
torch.norm(c, p=1, dim=-1)

tensor([13., 12.])

In [8]:
torch.sum(torch.abs(c), dim=-1)

tensor([13., 12.])

In [9]:
c.abs().sum(dim=-1)

tensor([13., 12.])

In [10]:
c.abs().sum(dim=-1, keepdim=True)

tensor([[13.],
        [12.]])

# tensor.norm(p=2, dim=n, keepdim=False) 求l2范数 p默认为2

每个值的平方和再开平方

$$
∥w∥_2^2
$$

In [11]:
c

tensor([[-2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-3., -2., -1.,  0.,  1.,  2.,  3.]])

In [12]:
c.norm(p=2, dim=-1)

tensor([5.9161, 5.2915])

In [13]:
# 保持维度不变
c.norm(p=2, dim=-1, keepdim=True)

tensor([[5.9161],
        [5.2915]])

In [14]:
torch.norm(c, dim=-1)

tensor([5.9161, 5.2915])

In [15]:
torch.sqrt(torch.sum(c ** 2, dim=-1))

tensor([5.9161, 5.2915])

In [16]:
(c ** 2).sum(dim=-1).sqrt()

tensor([5.9161, 5.2915])

In [17]:
c.square().sum(dim=-1).sqrt()

tensor([5.9161, 5.2915])

In [18]:
c.pow(2).sum(dim=-1).sqrt()

tensor([5.9161, 5.2915])

In [19]:
c.pow(2).sum(dim=-1, keepdim=True).sqrt()

tensor([[5.9161],
        [5.2915]])