In [3]:
import torch
from torch.nn import functional as F

# 将某一个维度除以那个维度对应的范数(默认是2范数)

In [13]:
x = torch.arange(10.).view(2, 5)
x

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

# 默认为l2 norm,在最后维度计算

In [14]:
F.normalize(x)

tensor([[0.0000, 0.1826, 0.3651, 0.5477, 0.7303],
        [0.3131, 0.3757, 0.4384, 0.5010, 0.5636]])

In [ ]:
F.normalize(x, p=2, dim=1)

tensor([[0.0000, 0.1826, 0.3651, 0.5477, 0.7303],
        [0.3131, 0.3757, 0.4384, 0.5010, 0.5636]])

In [26]:
x / x.norm(p=2, dim=1).unsqueeze(1)

tensor([[0.0000, 0.1826, 0.3651, 0.5477, 0.7303],
        [0.3131, 0.3757, 0.4384, 0.5010, 0.5636]])

# l1 norm

In [16]:
F.normalize(x, p=1)

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571]])

In [19]:
F.normalize(x, p=1, dim=1)

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571]])

In [27]:
x / x.norm(p=1, dim=1).unsqueeze(1)

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571]])

# dim=0

## l1 norm

In [30]:
F.normalize(x, p=1, dim=0)

tensor([[0.0000, 0.1429, 0.2222, 0.2727, 0.3077],
        [1.0000, 0.8571, 0.7778, 0.7273, 0.6923]])

In [31]:
x / x.norm(p=1, dim=0).unsqueeze(0)

tensor([[0.0000, 0.1429, 0.2222, 0.2727, 0.3077],
        [1.0000, 0.8571, 0.7778, 0.7273, 0.6923]])

## l2 norm

In [34]:
F.normalize(x, dim=0)

tensor([[0.0000, 0.1644, 0.2747, 0.3511, 0.4061],
        [1.0000, 0.9864, 0.9615, 0.9363, 0.9138]])

In [35]:
F.normalize(x, p=2, dim=0)

tensor([[0.0000, 0.1644, 0.2747, 0.3511, 0.4061],
        [1.0000, 0.9864, 0.9615, 0.9363, 0.9138]])

In [36]:
x / x.norm(p=2, dim=0).unsqueeze(0)

tensor([[0.0000, 0.1644, 0.2747, 0.3511, 0.4061],
        [1.0000, 0.9864, 0.9615, 0.9363, 0.9138]])