In [1]:
import torch

In [2]:
x = torch.arange(10, 21, 1)
x

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
x.nelement()

11

# torch.randperm(n) 整数随机排列,放入一个整数n,从 0~n-1 整数随机排列,可以当做index使用

In [6]:
index = torch.randperm(x.nelement())
index

tensor([ 1, 10,  2,  8,  7,  6,  0,  4,  3,  5,  9])

In [7]:
x[index]

tensor([11, 20, 12, 18, 17, 16, 10, 14, 13, 15, 19])