In [1]:
import torch

# reciprocal 倒数

$$
out_i = \frac 1 {input_i}
$$

In [5]:
x = torch.tensor([2, 4, 5])
x

tensor([2, 4, 5])

In [6]:
x.reciprocal()

tensor([0.5000, 0.2500, 0.2000])

In [7]:
torch.reciprocal(x)

tensor([0.5000, 0.2500, 0.2000])