In [39]:
import numpy as np
import torch

# Tri 矩阵左下角数据为1,右上角数据为0

## numpy

In [40]:
np.tri(4, 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [41]:
np.tri(5, 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.tri(5, 5, k=0)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.tri(5, 5, k=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.tri(5, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

## pytorch没有这个函数

# tril 保留矩阵左下角数据

## numpy

In [45]:
np.random.seed(0)
x = np.random.random((4, 4))
x

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [46]:
np.tril(x)

array([[0.5488135 , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [47]:
np.tril(x, k=0)

array([[0.5488135 , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [48]:
np.tril(x, k=1)

array([[0.5488135 , 0.71518937, 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.43758721, 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [49]:
np.tril(x, k=-1)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.        , 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.        , 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.        ]])

## torch

In [50]:
torch.manual_seed(0)
x = torch.randn((4, 4))
x

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [51]:
torch.tril(x)

tensor([[-1.1258,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.6920,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.0000],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [52]:
torch.tril(x, diagonal=0)

tensor([[-1.1258,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.6920,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.0000],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [53]:
torch.tril(x, diagonal=1)

tensor([[-1.1258, -1.1524,  0.0000,  0.0000],
        [ 0.8487,  0.6920, -0.3160,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [54]:
torch.tril(x, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.0000,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.0000,  0.0000],
        [ 0.1198,  1.2377,  1.1168,  0.0000]])

## 支持非方阵

In [55]:
np.random.seed(0)
x = np.random.random((4, 5))
np.tril(x, k=-1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.64589411, 0.        , 0.        , 0.        , 0.        ],
       [0.79172504, 0.52889492, 0.        , 0.        , 0.        ],
       [0.0871293 , 0.0202184 , 0.83261985, 0.        , 0.        ]])

In [56]:
torch.manual_seed(0)
x = torch.randn((4, 5))
torch.tril(x, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.5551,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.4437,  0.2660,  0.0000,  0.0000,  0.0000],
        [-0.8437,  0.9318,  1.2590,  0.0000,  0.0000]])

## 支持高维数据,在最后2个维度运算

In [57]:
np.random.seed(0)
x = np.random.random((2, 4, 4))
np.tril(x, k=-1)

array([[[0.        , 0.        , 0.        , 0.        ],
        [0.4236548 , 0.        , 0.        , 0.        ],
        [0.96366276, 0.38344152, 0.        , 0.        ],
        [0.56804456, 0.92559664, 0.07103606, 0.        ]],

       [[0.        , 0.        , 0.        , 0.        ],
        [0.97861834, 0.        , 0.        , 0.        ],
        [0.11827443, 0.63992102, 0.        , 0.        ],
        [0.52184832, 0.41466194, 0.26455561, 0.        ]]])

In [58]:
torch.manual_seed(0)
x = torch.randn((2, 4, 4))
torch.tril(x, diagonal=-1)

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.8487,  0.0000,  0.0000,  0.0000],
         [ 0.3223, -1.2633,  0.0000,  0.0000],
         [ 0.1198,  1.2377,  1.1168,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.5988,  0.0000,  0.0000,  0.0000],
         [ 0.7502, -0.5855,  0.0000,  0.0000],
         [ 1.3894,  1.5863,  0.9463,  0.0000]]])

# triu 保留矩阵右上角数据

## numpy

In [59]:
np.random.seed(0)
x = np.random.random((4, 4))
x

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [60]:
np.triu(x)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.79172504, 0.52889492],
       [0.        , 0.        , 0.        , 0.0871293 ]])

In [61]:
np.triu(x, k=0)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.79172504, 0.52889492],
       [0.        , 0.        , 0.        , 0.0871293 ]])

In [62]:
np.triu(x, k=1)

array([[0.        , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.        , 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.        , 0.52889492],
       [0.        , 0.        , 0.        , 0.        ]])

In [63]:
np.triu(x, k=-1)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.38344152, 0.79172504, 0.52889492],
       [0.        , 0.        , 0.07103606, 0.0871293 ]])

## torch

In [64]:
torch.manual_seed(0)
x = torch.randn((4, 4))
x

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [65]:
torch.triu(x)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.6920, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  0.0000, -0.2473]])

In [66]:
torch.triu(x, diagonal=0)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.6920, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  0.0000, -0.2473]])

In [67]:
torch.triu(x, diagonal=1)

tensor([[ 0.0000, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.0000, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.0000,  0.3081],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [68]:
torch.triu(x, diagonal=-1)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.0000, -1.2633,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  1.1168, -0.2473]])

## 支持非方阵

In [69]:
np.random.seed(0)
x = np.random.random((4, 5))
np.triu(x, k=1)

array([[0.        , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.        , 0.        , 0.891773  , 0.96366276, 0.38344152],
       [0.        , 0.        , 0.        , 0.92559664, 0.07103606],
       [0.        , 0.        , 0.        , 0.        , 0.87001215]])

In [70]:
torch.manual_seed(0)
x = torch.randn((4, 5))
torch.triu(x, diagonal=1)

tensor([[ 0.0000, -1.1524, -0.2506, -0.4339,  0.5988],
        [ 0.0000,  0.0000,  1.8530,  0.4681, -0.1577],
        [ 0.0000,  0.0000,  0.0000,  1.5863,  0.9463],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0537]])

## 支持高维数据,在最后2个维度运算

In [71]:
np.random.seed(0)
x = np.random.random((2, 4, 4))
np.triu(x, k=1)

array([[[0.        , 0.71518937, 0.60276338, 0.54488318],
        [0.        , 0.        , 0.43758721, 0.891773  ],
        [0.        , 0.        , 0.        , 0.52889492],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.        , 0.83261985, 0.77815675, 0.87001215],
        [0.        , 0.        , 0.46147936, 0.78052918],
        [0.        , 0.        , 0.        , 0.94466892],
        [0.        , 0.        , 0.        , 0.        ]]])

In [72]:
torch.manual_seed(0)
x = torch.randn((2, 4, 4))
torch.triu(x, diagonal=1)

tensor([[[ 0.0000, -1.1524, -0.2506, -0.4339],
         [ 0.0000,  0.0000, -0.3160, -2.1152],
         [ 0.0000,  0.0000,  0.0000,  0.3081],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000, -1.6959,  0.5667,  0.7935],
         [ 0.0000,  0.0000, -0.3414,  1.8530],
         [ 0.0000,  0.0000,  0.0000,  0.1835],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])

# Transformer Attention Mask
![](./Transformer%20Attention%20Mask.jpg)

## numpy

In [77]:
x = np.full((5, 5), -np.inf)
x

array([[-inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf]])

In [78]:
np.triu(x, k=1)

array([[  0., -inf, -inf, -inf, -inf],
       [  0.,   0., -inf, -inf, -inf],
       [  0.,   0.,   0., -inf, -inf],
       [  0.,   0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.,   0.]])

## torch

In [79]:
x = torch.full((5, 5), -torch.inf)
x

tensor([[-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf]])

In [80]:
x.triu(diagonal=1)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

## 注意力范围mask

In [ ]:
base_mask = torch.full(torch.Size([10, 10]), -torch.inf)
base_mask

tensor([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]])

In [ ]:
torch.triu(base_mask, 1)

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
torch.tril(base_mask, -5)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [-inf, 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [-inf, -inf, 0., 0., 0., 0., 0., 0., 0., 0.],
        [-inf, -inf, -inf, 0., 0., 0., 0., 0., 0., 0.],
        [-inf, -inf, -inf, -inf, 0., 0., 0., 0., 0., 0.],
        [-inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0., 0.]])

In [ ]:
# 注意力长度为5
torch.triu(base_mask, 1) + torch.tril(base_mask, -5)

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [-inf, 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [-inf, -inf, 0., 0., 0., 0., 0., -inf, -inf, -inf],
        [-inf, -inf, -inf, 0., 0., 0., 0., 0., -inf, -inf],
        [-inf, -inf, -inf, -inf, 0., 0., 0., 0., 0., -inf],
        [-inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0., 0.]])