In [1]:
import numpy as np
import torch

# Tri

## numpy

In [24]:
np.tri(4, 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [25]:
np.tri(5, 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.tri(5, 5, k=0)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.tri(5, 5, k=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.tri(5, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

## pytorch没有这个函数

# tril 保留矩阵做下角数据

## numpy

In [82]:
np.random.seed(0)
x = np.random.random((4, 4))
x

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [83]:
np.tril(x)

array([[0.5488135 , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [84]:
np.tril(x, k=0)

array([[0.5488135 , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [85]:
np.tril(x, k=1)

array([[0.5488135 , 0.71518937, 0.        , 0.        ],
       [0.4236548 , 0.64589411, 0.43758721, 0.        ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [86]:
np.tril(x, k=-1)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.4236548 , 0.        , 0.        , 0.        ],
       [0.96366276, 0.38344152, 0.        , 0.        ],
       [0.56804456, 0.92559664, 0.07103606, 0.        ]])

## torch

In [98]:
torch.manual_seed(0)
x = torch.randn((4, 4))
x

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [99]:
torch.tril(x)

tensor([[-1.1258,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.6920,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.0000],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [100]:
torch.tril(x, diagonal=0)

tensor([[-1.1258,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.6920,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.0000],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [101]:
torch.tril(x, diagonal=1)

tensor([[-1.1258, -1.1524,  0.0000,  0.0000],
        [ 0.8487,  0.6920, -0.3160,  0.0000],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [102]:
torch.tril(x, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8487,  0.0000,  0.0000,  0.0000],
        [ 0.3223, -1.2633,  0.0000,  0.0000],
        [ 0.1198,  1.2377,  1.1168,  0.0000]])

## 支持非方阵

In [131]:
np.random.seed(0)
x = np.random.random((4, 5))
np.tril(x, k=-1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.64589411, 0.        , 0.        , 0.        , 0.        ],
       [0.79172504, 0.52889492, 0.        , 0.        , 0.        ],
       [0.0871293 , 0.0202184 , 0.83261985, 0.        , 0.        ]])

In [132]:
torch.manual_seed(0)
x = torch.randn((4, 5))
torch.tril(x, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.5551,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.4437,  0.2660,  0.0000,  0.0000,  0.0000],
        [-0.8437,  0.9318,  1.2590,  0.0000,  0.0000]])

## 支持高维数据,在最后2个维度运算

In [130]:
np.random.seed(0)
x = np.random.random((2, 4, 4))
np.tril(x, k=-1)

array([[[0.        , 0.        , 0.        , 0.        ],
        [0.4236548 , 0.        , 0.        , 0.        ],
        [0.96366276, 0.38344152, 0.        , 0.        ],
        [0.56804456, 0.92559664, 0.07103606, 0.        ]],

       [[0.        , 0.        , 0.        , 0.        ],
        [0.97861834, 0.        , 0.        , 0.        ],
        [0.11827443, 0.63992102, 0.        , 0.        ],
        [0.52184832, 0.41466194, 0.26455561, 0.        ]]])

In [133]:
torch.manual_seed(0)
x = torch.randn((2, 4, 4))
torch.tril(x, diagonal=-1)

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.8487,  0.0000,  0.0000,  0.0000],
         [ 0.3223, -1.2633,  0.0000,  0.0000],
         [ 0.1198,  1.2377,  1.1168,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.5988,  0.0000,  0.0000,  0.0000],
         [ 0.7502, -0.5855,  0.0000,  0.0000],
         [ 1.3894,  1.5863,  0.9463,  0.0000]]])

# triu 保留矩阵右上角数据

## numpy

In [64]:
np.random.seed(0)
x = np.random.random((4, 4))
x

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [65]:
np.triu(x)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.79172504, 0.52889492],
       [0.        , 0.        , 0.        , 0.0871293 ]])

In [66]:
np.triu(x, k=0)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.79172504, 0.52889492],
       [0.        , 0.        , 0.        , 0.0871293 ]])

In [67]:
np.triu(x, k=1)

array([[0.        , 0.71518937, 0.60276338, 0.54488318],
       [0.        , 0.        , 0.43758721, 0.891773  ],
       [0.        , 0.        , 0.        , 0.52889492],
       [0.        , 0.        , 0.        , 0.        ]])

In [68]:
np.triu(x, k=-1)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.        , 0.38344152, 0.79172504, 0.52889492],
       [0.        , 0.        , 0.07103606, 0.0871293 ]])

## torch

In [69]:
torch.manual_seed(0)
x = torch.randn((4, 4))
x

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])

In [70]:
torch.triu(x)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.6920, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  0.0000, -0.2473]])

In [71]:
torch.triu(x, diagonal=0)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.6920, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  0.0000, -0.2473]])

In [72]:
torch.triu(x, diagonal=1)

tensor([[ 0.0000, -1.1524, -0.2506, -0.4339],
        [ 0.0000,  0.0000, -0.3160, -2.1152],
        [ 0.0000,  0.0000,  0.0000,  0.3081],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [74]:
torch.triu(x, diagonal=-1)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.0000, -1.2633,  0.3500,  0.3081],
        [ 0.0000,  0.0000,  1.1168, -0.2473]])

## 支持非方阵

In [124]:
np.random.seed(0)
x = np.random.random((4, 5))
np.triu(x, k=1)

array([[0.        , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.        , 0.        , 0.891773  , 0.96366276, 0.38344152],
       [0.        , 0.        , 0.        , 0.92559664, 0.07103606],
       [0.        , 0.        , 0.        , 0.        , 0.87001215]])

In [125]:
torch.manual_seed(0)
x = torch.randn((4, 5))
torch.triu(x, diagonal=1)

tensor([[ 0.0000, -1.1524, -0.2506, -0.4339,  0.5988],
        [ 0.0000,  0.0000,  1.8530,  0.4681, -0.1577],
        [ 0.0000,  0.0000,  0.0000,  1.5863,  0.9463],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0537]])

## 支持高维数据,在最后2个维度运算

In [126]:
np.random.seed(0)
x = np.random.random((2, 4, 4))
np.triu(x, k=1)

array([[[0.        , 0.71518937, 0.60276338, 0.54488318],
        [0.        , 0.        , 0.43758721, 0.891773  ],
        [0.        , 0.        , 0.        , 0.52889492],
        [0.        , 0.        , 0.        , 0.        ]],

       [[0.        , 0.83261985, 0.77815675, 0.87001215],
        [0.        , 0.        , 0.46147936, 0.78052918],
        [0.        , 0.        , 0.        , 0.94466892],
        [0.        , 0.        , 0.        , 0.        ]]])

In [127]:
torch.manual_seed(0)
x = torch.randn((2, 4, 4))
torch.triu(x, diagonal=1)

tensor([[[ 0.0000, -1.1524, -0.2506, -0.4339],
         [ 0.0000,  0.0000, -0.3160, -2.1152],
         [ 0.0000,  0.0000,  0.0000,  0.3081],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000, -1.6959,  0.5667,  0.7935],
         [ 0.0000,  0.0000, -0.3414,  1.8530],
         [ 0.0000,  0.0000,  0.0000,  0.1835],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])

# Transformer Attention Mask
![](./Transformer%20Attention%20Mask.jpg)

## numpy

In [109]:
x = np.full((4, 4), -np.inf)
x

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [110]:
np.triu(x, k=1)

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

## torch

In [111]:
x = torch.full((4, 4), -torch.inf)
x

tensor([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]])

In [112]:
x.triu(diagonal=1)

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])