In [19]:
import numpy as np

In [20]:
A = np.arange(16.0).reshape((4, 4))
B = np.arange(16.0).reshape((4, 4))
A, B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]))

In [21]:
C = A @ B
C

array([[ 56.,  62.,  68.,  74.],
       [152., 174., 196., 218.],
       [248., 286., 324., 362.],
       [344., 398., 452., 506.]])

# 列并行

<img src="test.assets/model-parallelism%20%E5%BC%A0%E9%87%8F%E5%B9%B6%E8%A1%8C%20%E5%88%97%E5%B9%B6%E8%A1%8C%202.png" alt="列并行" style="zoom:33%;" />

In [22]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [23]:
B_col1, B_col2 = np.split(B, 2, axis=1)
B_col1, B_col2

(array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]]))

In [24]:
C1 = np.concatenate([A @ B_col1, A @ B_col2], axis=1)
C1

array([[ 56.,  62.,  68.,  74.],
       [152., 174., 196., 218.],
       [248., 286., 324., 362.],
       [344., 398., 452., 506.]])

In [25]:
np.all(C == C1)

True

# 行并行

<img src="test.assets/model-parallelism%20%E5%BC%A0%E9%87%8F%E5%B9%B6%E8%A1%8C%20%E8%A1%8C%E5%B9%B6%E8%A1%8C%202.png" alt="model-parallelism 张量并行 行并行 2" style="zoom:33%;" />

In [26]:
A_col1, A_col2 = np.split(A, 2, axis=1)
A_col1, A_col2

(array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]]))

In [27]:
B_row1, B_row2 = np.split(B, 2, axis=0)
B_row1, B_row2

(array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]))

In [28]:
C2 = A_col1 @ B_row1 + A_col2 @ B_row2

In [18]:
np.all(C == C2)

True