In [27]:
import torch
from torch import nn
from torch.nn import functional as F

# BatchNorm2d

In [28]:
bn2d = nn.BatchNorm2d(2)

In [29]:
# running_mean
bn2d.running_mean.data

tensor([0., 0.])

In [30]:
# running_var
bn2d.running_var.data

tensor([1., 1.])

In [31]:
# gamma
bn2d.weight.data

tensor([1., 1.])

In [32]:
# beta
bn2d.bias.data

tensor([0., 0.])

In [34]:
# eps
bn2d.eps

1e-05

# 运算

In [11]:
x = torch.arange(1, 51.).reshape(1, 2, 5, 5)
x

tensor([[[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.],
          [11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25.]],

         [[26., 27., 28., 29., 30.],
          [31., 32., 33., 34., 35.],
          [36., 37., 38., 39., 40.],
          [41., 42., 43., 44., 45.],
          [46., 47., 48., 49., 50.]]]])

In [12]:
x.shape

torch.Size([1, 2, 5, 5])

In [13]:
bn2d(x)

tensor([[[[-1.6641, -1.5254, -1.3868, -1.2481, -1.1094],
          [-0.9707, -0.8321, -0.6934, -0.5547, -0.4160],
          [-0.2773, -0.1387,  0.0000,  0.1387,  0.2774],
          [ 0.4160,  0.5547,  0.6934,  0.8321,  0.9707],
          [ 1.1094,  1.2481,  1.3868,  1.5254,  1.6641]],

         [[-1.6641, -1.5254, -1.3868, -1.2481, -1.1094],
          [-0.9707, -0.8321, -0.6934, -0.5547, -0.4160],
          [-0.2774, -0.1387,  0.0000,  0.1387,  0.2773],
          [ 0.4160,  0.5547,  0.6934,  0.8321,  0.9707],
          [ 1.1094,  1.2481,  1.3868,  1.5254,  1.6641]]]],
       grad_fn=<NativeBatchNormBackward0>)