In [18]:
import numpy as np
import torch

# 1.torch.tensor(data) 创建张量

Tensor和tensor都能创建

1. 全局默认数据类型是torch.float32
2. torch.Tensor()传入数字表示形状,和torch.FloatTensor相同
3. torch.Tensor传入可迭代对象表示数据,类型为模型的数据类型
4. torch.tensor为默认的创建方法


## 列表创建

In [19]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

## numpy数组创建

使用numpy中的数组创建tensor

In [20]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [21]:
torch.from_numpy(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 使用torch的api创建tensor

### 填充数据

#### torch.empty(*sizes) 全为空

In [22]:
torch.empty(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### torch.ones(*sizes) 全为1

In [23]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### torch.ones_like(tensor) 全为1,形状为tensor的形状

In [24]:
a = torch.rand(2, 2)
torch.ones_like(a)

tensor([[1., 1.],
        [1., 1.]])

#### torch.zeros(*sizes) 全为0

In [25]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### torch.zeros_like(tensor) 全为0,形状为tensor的形状

In [26]:
a = torch.rand(2, 2)
torch.zeros_like(a)

tensor([[0., 0.],
        [0., 0.]])

#### torch.full(*sizes, num) 用num填满形状

In [27]:
torch.full([2, 3], 1.5)

tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])

### 随机数

#### torch.rand(*sizes, out=None) → Tensor 均匀分布 0-1随机值

In [28]:
torch.rand([3, 5])

tensor([[0.6705, 0.5345, 0.4552, 0.4165, 0.5157],
        [0.8620, 0.4791, 0.5162, 0.8175, 0.0058],
        [0.8765, 0.9136, 0.9443, 0.8994, 0.1937]])

#### torch.randint(low, high, *sizes) → Tensor 均匀分布 随机整数指定区间

In [29]:
torch.randint(1, 10, [2, 4])

tensor([[7, 9, 7, 3],
        [1, 6, 9, 8]])

#### torch.randn(*sizes, out=None) → Tensor 标准正态分布

In [30]:
torch.randn([3, 4])

tensor([[-0.9316,  0.9231,  0.7255,  0.5613],
        [-0.5890,  1.1253, -0.4761, -1.1915],
        [ 1.6976, -1.8023, -0.8442, -0.1488]])

#### torch.normal(means, std, out=None)

**参数:**

- means (float, optional) - 均值
- std (Tensor) - 标准差
- out (Tensor) - 输出张量

In [31]:
torch.normal(5, 3, [3, 4])

tensor([[2.9126, 9.5728, 1.6168, 9.6085],
        [3.0272, 6.6160, 5.1433, 7.3127],
        [0.0718, 3.9609, 9.4840, 6.0789]])

# 转移数据到设备

In [32]:
torch.cuda.is_available()

True

In [33]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [34]:
torch.zeros([2, 3], device=device)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [35]:
arr = torch.ones(2, 3)
arr

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
arr = arr.to(device)
arr

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')