In [2]:
import numpy as np
import torch

# 1.列表,切片

In [17]:
arr = torch.arange(1, 25).reshape(2, 3, 4)
arr

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [18]:
arr[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [19]:
arr[0:1]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [20]:
arr[:, 0]

tensor([[ 1,  2,  3,  4],
        [13, 14, 15, 16]])

In [21]:
arr[:, 0:2]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20]]])

In [22]:
arr[..., 1]

tensor([[ 2,  6, 10],
        [14, 18, 22]])

### None的作用

In [23]:
arr[None, :]

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]])

In [24]:
arr[None, :] == arr[:, :]

tensor([[[[True, True, True, True],
          [True, True, True, True],
          [True, True, True, True]],

         [[True, True, True, True],
          [True, True, True, True],
          [True, True, True, True]]]])

In [25]:
arr[:, None]

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]],


        [[[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]])

In [26]:
arr[:, None] == arr[:, :]

tensor([[[[ True,  True,  True,  True],
          [ True,  True,  True,  True],
          [ True,  True,  True,  True]],

         [[False, False, False, False],
          [False, False, False, False],
          [False, False, False, False]]],


        [[[False, False, False, False],
          [False, False, False, False],
          [False, False, False, False]],

         [[ True,  True,  True,  True],
          [ True,  True,  True,  True],
          [ True,  True,  True,  True]]]])

### 切片赋值

In [23]:
arr[0, 0, 0] = 999
arr

tensor([[[999,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23,  24]]])

In [25]:
arr[:, 0] = -1
arr

tensor([[[-1, -1, -1, -1],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[-1, -1, -1, -1],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [29]:
arr[[0, 1]]

tensor([[[-1, -1, -1, -1],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[-1, -1, -1, -1],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [28]:
arr[:, [0, 1]]

tensor([[[-1, -1, -1, -1],
         [ 5,  6,  7,  8]],

        [[-1, -1, -1, -1],
         [17, 18, 19, 20]]])

### 多维度切片

In [33]:
arr[[]]

tensor([], size=(0, 3, 4), dtype=torch.int64)

In [34]:
arr[[0]]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [36]:
arr[[1]]

tensor([[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [38]:
# 取反 tensor(1) 为 tensor(0) 获取0的输出
arr[~torch.tensor(1)]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [35]:
arr[[0, 1]]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

# 2.tensor.item() 获取tensor中的数据(当tensor中只有一个元素可用)

In [9]:
arr.item()

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
x = torch.ones([1, 1])
x

tensor([[1.]])

In [ ]:
x.item()

1.0

# 3.tensor.data() 取出tensor中的值忽略梯度信息

In [10]:
arr1 = torch.arange(1.0, 25, requires_grad=True).reshape(2, 3, 4)
arr1

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]], grad_fn=<ReshapeAliasBackward0>)

In [11]:
arr1.data

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

# 4.tensor.datach() 去除梯度信息

In [12]:
arr1.detach()

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

# 5.torch 转化为 numpy 数组

In [13]:
arr1.detach().numpy()

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)

In [14]:
# 必须要剔除梯度
arr1.detach().numpy()

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)