In [1]:
import torch

# 等差-步长 torch.arange(start, end , step)

- 创建等差数组 — 指定步长
- 参数
  - start: 序列的起始值
  - end : 序列的终止值(不包含)
  - step:步长,默认值为1

In [2]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [3]:
torch.arange(0, 11, 1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 只有一个参数n, 结果从0到n-1

In [4]:
torch.arange(11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 等差-数量 torch.linspace(start, end , steps)

- 创建等差数组 — 指定数量
- 参数:
  - start: 序列的起始值
  - end : 序列的终止值(包含)
  - steps: 要生成的等间隔样例数量

In [7]:
torch.linspace(0, 100, 11)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## 等比 torch.logspace(start, end, steps, base)

- 创建等比数列
- 参数:
  - start: **指数位**的开始指数
  - end : **指数位**的终止指数(包含)
  - steps: 要生成的等比数列数量
  - base: 以谁为底,默认为10

In [8]:
torch.logspace(0, 2, 3)

tensor([  1.,  10., 100.])

In [9]:
torch.logspace(0, 2, 3, torch.e)

tensor([1.0000, 2.7183, 7.3891])