In [9]:
import torch
torch.manual_seed(0)

# 创建时指定 dtype

In [10]:
torch.tensor([2, 3], dtype=torch.float)

tensor([2., 3.])

In [11]:
x = torch.randn((1, 2, 3), dtype=torch.float16)
x

tensor([[[ 1.5410, -0.2935, -2.1797],
         [ 0.5684, -1.0850, -1.3984]]], dtype=torch.float16)

In [12]:
x.dtype

torch.float16

In [13]:
x.dtype = torch.float32
# 错误,不能这样修改

AttributeError: attribute 'dtype' of 'torch._C._TensorBase' objects is not writable

# 通过 tensor.float() tensor.int() 更改类型

In [18]:
x.float()

tensor([[[ 1.5410, -0.2935, -2.1797],
         [ 0.5684, -1.0850, -1.3984]]])

In [19]:
x.int()

tensor([[[ 1,  0, -2],
         [ 0, -1, -1]]], dtype=torch.int32)

# 通过 tensor.type(new_type) 更改类型

In [14]:
x.type(torch.float32)

tensor([[[ 1.5410, -0.2935, -2.1797],
         [ 0.5684, -1.0850, -1.3984]]])

# 通过 tensor.type_as(tensor) 更改类型

In [15]:
y = torch.randn(1, dtype=torch.float64)
y

tensor([0.4033], dtype=torch.float64)

In [16]:
x.type_as(y)

tensor([[[ 1.5410, -0.2935, -2.1797],
         [ 0.5684, -1.0850, -1.3984]]], dtype=torch.float64)