In [51]:
import torch
torch.manual_seed(0)

# 创建时指定 dtype

In [52]:
torch.tensor([2, 3], dtype=torch.float)

tensor([2., 3.])

In [53]:
torch.tensor([2, 3], dtype=torch.float32)

tensor([2., 3.])

In [54]:
x = torch.randn((1, 2, 3), dtype=torch.float16)
x

tensor([[[ 1.5410, -0.2935, -2.1797],
         [ 0.5684, -1.0850, -1.3984]]], dtype=torch.float16)

In [55]:
x = torch.randn((1, 2, 3), dtype=torch.float64)
x

tensor([[[ 0.4033,  0.8380, -0.7193],
         [-0.4033, -0.5966,  0.1820]]], dtype=torch.float64)

In [56]:
x.dtype

torch.float64

In [57]:
try:
    x.dtype = torch.float32
except:
    print("`x.dtype = torch.float32` 这样修改是错误的")

`x.dtype = torch.float32` 这样修改是错误的


# 通过 tensor.float() tensor.int() 更改类型

In [58]:
x.float()

tensor([[[ 0.4033,  0.8380, -0.7193],
         [-0.4033, -0.5966,  0.1820]]])

In [59]:
x.half()

tensor([[[ 0.4033,  0.8379, -0.7192],
         [-0.4033, -0.5967,  0.1820]]], dtype=torch.float16)

In [60]:
x.bfloat16()

tensor([[[ 0.4043,  0.8398, -0.7188],
         [-0.4043, -0.5977,  0.1816]]], dtype=torch.bfloat16)

In [61]:
x.int()

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

# 通过 tensor.type(new_type) 更改类型

In [62]:
x.type(torch.float16)

tensor([[[ 0.4033,  0.8379, -0.7192],
         [-0.4033, -0.5967,  0.1820]]], dtype=torch.float16)

In [63]:
x.type(torch.bfloat16)

tensor([[[ 0.4043,  0.8398, -0.7188],
         [-0.4043, -0.5977,  0.1816]]], dtype=torch.bfloat16)

In [64]:
x.type(torch.float32)

tensor([[[ 0.4033,  0.8380, -0.7193],
         [-0.4033, -0.5966,  0.1820]]])

In [65]:
x.type(torch.float64)

tensor([[[ 0.4033,  0.8380, -0.7193],
         [-0.4033, -0.5966,  0.1820]]], dtype=torch.float64)

In [66]:
x.type(torch.int8)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int8)

In [67]:
x.type(torch.uint8)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.uint8)

In [68]:
x.type(torch.int16)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int16)

In [69]:
x.type(torch.int)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [70]:
x.type(torch.int32)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [71]:
x.type(torch.int64)

tensor([[[0, 0, 0],
         [0, 0, 0]]])

# 通过 tensor.type_as(tensor) 更改类型

In [72]:
y = torch.randn(1, dtype=torch.bfloat16)
y

tensor([-0.8555], dtype=torch.bfloat16)

In [73]:
x.type_as(y)

tensor([[[ 0.4043,  0.8398, -0.7188],
         [-0.4043, -0.5977,  0.1816]]], dtype=torch.bfloat16)