In [1]:
import torch
from torch import nn
from torch.nn import functional as F

# 实例化Conv3d

In [2]:
conv3d = nn.Conv3d(
    in_channels=3,
    out_channels=1,
    kernel_size=3,
    stride=2,
    padding=1,
    dilation=1,
    groups=1,
    bias=True,
)
conv3d.eval()

Conv3d(3, 1, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))

## 初始化方式1

In [3]:
def init_weights(m):
    if type(m) == nn.Conv3d:
        nn.init.normal_(m.weight, mean=0, std=0.01)

In [4]:
conv3d.apply(init_weights)

Conv3d(3, 1, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))

# 查看并设置Conv3d的weight和bias(初始化方式2)

In [3]:
conv3d.weight.data.normal_(0, 0.01)

tensor([[[[[ 0.0130,  0.0005, -0.0251],
           [ 0.0013, -0.0079, -0.0027],
           [ 0.0066,  0.0019, -0.0061]],

          [[ 0.0119,  0.0108,  0.0127],
           [-0.0009, -0.0138,  0.0039],
           [ 0.0081,  0.0155, -0.0055]],

          [[ 0.0015, -0.0004,  0.0063],
           [ 0.0026,  0.0003,  0.0192],
           [-0.0112,  0.0040, -0.0186]]],


         [[[ 0.0128,  0.0096, -0.0022],
           [ 0.0245,  0.0027,  0.0029],
           [-0.0060,  0.0039,  0.0143]],

          [[ 0.0018,  0.0091, -0.0112],
           [-0.0140,  0.0196, -0.0042],
           [ 0.0119, -0.0039, -0.0082]],

          [[-0.0135, -0.0197,  0.0205],
           [-0.0014, -0.0056, -0.0043],
           [ 0.0185, -0.0067,  0.0120]]],


         [[[ 0.0133,  0.0077,  0.0057],
           [-0.0059, -0.0117, -0.0005],
           [ 0.0039,  0.0153, -0.0063]],

          [[-0.0184,  0.0109,  0.0058],
           [-0.0122,  0.0056, -0.0076],
           [ 0.0045, -0.0099,  0.0134]],

          [[ 0.0024,

In [4]:
conv3d.weight.data

tensor([[[[[ 0.0130,  0.0005, -0.0251],
           [ 0.0013, -0.0079, -0.0027],
           [ 0.0066,  0.0019, -0.0061]],

          [[ 0.0119,  0.0108,  0.0127],
           [-0.0009, -0.0138,  0.0039],
           [ 0.0081,  0.0155, -0.0055]],

          [[ 0.0015, -0.0004,  0.0063],
           [ 0.0026,  0.0003,  0.0192],
           [-0.0112,  0.0040, -0.0186]]],


         [[[ 0.0128,  0.0096, -0.0022],
           [ 0.0245,  0.0027,  0.0029],
           [-0.0060,  0.0039,  0.0143]],

          [[ 0.0018,  0.0091, -0.0112],
           [-0.0140,  0.0196, -0.0042],
           [ 0.0119, -0.0039, -0.0082]],

          [[-0.0135, -0.0197,  0.0205],
           [-0.0014, -0.0056, -0.0043],
           [ 0.0185, -0.0067,  0.0120]]],


         [[[ 0.0133,  0.0077,  0.0057],
           [-0.0059, -0.0117, -0.0005],
           [ 0.0039,  0.0153, -0.0063]],

          [[-0.0184,  0.0109,  0.0058],
           [-0.0122,  0.0056, -0.0076],
           [ 0.0045, -0.0099,  0.0134]],

          [[ 0.0024,

In [5]:
conv3d.bias.data.fill_(0)

tensor([0.])

In [6]:
conv3d.bias.data

tensor([0.])

# 自动推理

In [18]:
x = torch.rand(10, 3, 224, 224, 224)
x.size()

torch.Size([10, 3, 224, 224, 224])

In [19]:
with torch.inference_mode():
    y = conv3d(x)
y.size()
# 因为stride=2,所以后面3个通道都减半了

torch.Size([10, 1, 112, 112, 112])

# 手动计算