In [1]:
import torch
from torch import nn
from torch.nn import functional as F

# 实例化Conv1d

In [2]:
conv1d = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1, padding=1, dilation=1, groups=1, bias=True)
conv1d.eval()

Conv1d(2, 1, kernel_size=(3,), stride=(1,), padding=(1,))

## 初始化方式1

In [3]:
def init_weights(m):
    if type(m) == nn.Conv1d:
        nn.init.normal_(m.weight, mean=0, std=0.01)

In [4]:
conv1d.apply(init_weights)

Conv1d(2, 1, kernel_size=(3,), stride=(1,), padding=(1,))

# 查看并设置Conv2d的weight和bias(初始化方式2)

In [5]:
conv1d.weight.data.normal_(0, 0.01)

tensor([[[-0.0193, -0.0018,  0.0080],
         [ 0.0071,  0.0152, -0.0065]]])

In [6]:
conv1d.weight.data

tensor([[[-0.0193, -0.0018,  0.0080],
         [ 0.0071,  0.0152, -0.0065]]])

In [7]:
conv1d.bias.data.fill_(0)

tensor([0.])

In [8]:
conv1d.bias.data

tensor([0.])

# 自动推理

In [9]:
x = torch.arange(1, 21.).reshape(1, 2, 10)
x

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]]])

In [10]:
x.shape
# (B, C, L)

torch.Size([1, 2, 10])

In [11]:
with torch.inference_mode():
    y = conv1d(x)
y

tensor([[[ 0.1498,  2.8126,  3.0094,  3.2061,  3.4029,  3.5997,  3.7965,
           3.9933,  4.1901, -3.9429]]])

# 手动计算

In [12]:
(x[:, :, :3] * conv1d.weight.data + conv1d.bias.data).sum()

tensor(2.7988)