https://github.com/lllyasviel/ControlNet

The "zero convolution" is 1×1 convolution with both weight and bias initialized as zeros.

In [1]:
import torch
from torch import nn

In [13]:
conv = nn.Conv2d(3, 3, 1)
conv.weight.data = torch.zeros(conv.weight.data.shape)
conv.weight.data.shape

torch.Size([3, 3, 1, 1])

In [14]:
conv.bias.data = torch.zeros(conv.bias.data.shape)
conv.bias.data

tensor([0., 0., 0.])

In [15]:
x = torch.randn(1, 3, 2, 2)
x

tensor([[[[-1.1356, -1.9665],
          [-0.2663, -1.1743]],

         [[ 2.1061, -0.0550],
          [-0.5046,  0.1418]],

         [[ 1.1863,  0.0971],
          [-0.2590,  1.2334]]]])

In [16]:
conv(x)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], grad_fn=<ConvolutionBackward0>)