In [2]:
import torch

In [3]:
arr = torch.arange(1, 13, 1).reshape(2, 6)
arr

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

#  tensor.max/min(dim=num) 给了dim就返回值和下标

### 没有参数的话会将数据变为一维,求最大/小值

In [4]:
arr.max()

tensor(12)

In [5]:
arr.max(dim=1)

torch.return_types.max(
values=tensor([ 6, 12]),
indices=tensor([5, 5]))

## tensor.max / min(dim=num, keepdim=True)

In [6]:
arr.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[ 6],
        [12]]),
indices=tensor([[5],
        [5]]))

In [7]:
max_values, indices = arr.max(dim=1, keepdim=True)

In [8]:
max_values

tensor([[ 6],
        [12]])

In [9]:
indices

tensor([[5],
        [5]])

### 在数据中取出max下标的方法

> 是否使用 keepdim=True 会对最后输出的数据维度有影响

In [55]:
for ar, i in zip(arr, arr.max(dim=1)[1]):
    print(i, ar[i])

tensor(5) tensor(6)
tensor(5) tensor(12)


In [56]:
for ar, i in zip(arr, arr.max(dim=1, keepdim=True)[1]):
    print(i, ar[i])

tensor([5]) tensor([6])
tensor([5]) tensor([12])


## tensor.argmax / argmin(dim=维度, keepdim=True)  最大值,最小值索引

In [10]:
arr.argmax()

tensor(11)

In [11]:
arr.argmax(dim=1)

tensor([5, 5])

In [52]:
arr.argmax(dim=1, keepdim=True)

tensor([[5],
        [5]])

In [46]:
arr

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

### 在数据中取出argmax下标的方法

> 是否使用 keepdim=True 会对最后输出的数据维度有影响

In [53]:
for ar, i in zip(arr, arr.argmax(dim=1)):
    print(i, ar[i])

tensor(5) tensor(6)
tensor(5) tensor(12)


In [54]:
for ar, i in zip(arr, arr.argmax(dim=1, keepdim=True)):
    print(i, ar[i])

tensor([5]) tensor([6])
tensor([5]) tensor([12])


## 图像分类实例

In [37]:
names = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
pred_class = torch.randn(4, 10)
pred_class

tensor([[-0.1295,  1.3927,  0.3477,  2.1047, -0.3088,  1.2367,  0.4375, -0.1354,
          0.9064, -1.0226],
        [-1.6720,  0.9562,  0.8725, -0.3480,  0.0484, -0.0963, -0.2982,  1.1832,
         -0.2839, -0.7568],
        [ 0.5597, -1.6683,  0.6186,  0.0396, -0.8694, -0.5320, -0.2491, -0.9964,
         -0.1184,  0.8904],
        [-0.2143,  2.5097, -1.2449, -0.7533,  0.7665, -1.6161, -2.1258,  0.9379,
          0.5714,  2.3242]])

In [38]:
pred_class.argmax(dim=-1)

tensor([3, 7, 9, 1])

In [63]:
for i in pred_class.argmax(dim=-1):
    print(names[i])

D
H
J
B
