In [1]:
import torch

# 1 tensor.view(new_shape) / tensor.reshape(new_shape) 改变形状

形状改变：`tensor.view() or reshape()`类似numpy中的reshape，是一种浅拷贝

1 view只能对连续内存的数据转换维度(浅拷贝)

​	view是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置，这样避免了重新创建张量的高内存开销。

2 contiguous()会开辟新的内存空间

3 reshape()可以对不连续内存数据进行处理

​	reshape可以开辟新的内存空间

​	tensor内存连续， **a.reshape()**返回的结果与**a.view()**相同，

​	tensor内存不连续,**a.reshape()**返回的结果与**a.view().contiguous()**相同。

In [9]:
arr = torch.arange(1, 13.)
arr

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [10]:
arr.view(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [11]:
arr.reshape(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [12]:
arr1 = arr.view(2, 3, 2)
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

## 经过转置之后的数据不连续,没法使用 view() 函数,要使用 contiguous().view() 或者使用 reshape()

In [13]:
arr2 = arr1.transpose(1, 2)
arr2

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

In [16]:
# 报错
arr2.view(2, 6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [17]:
# 必须使用连续区域
arr2.contiguous().view(2, 6)

tensor([[ 1.,  3.,  5.,  2.,  4.,  6.],
        [ 7.,  9., 11.,  8., 10., 12.]])

In [18]:
arr2.reshape(2, 6)

tensor([[ 1.,  3.,  5.,  2.,  4.,  6.],
        [ 7.,  9., 11.,  8., 10., 12.]])

## view(-1, 1) 和 reshape(-1, 1) 将行向量调整为列向量

In [22]:
arr

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [23]:
arr.view(-1, 1), arr.view(-1, 1).shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [24]:
arr.reshape(-1, 1), arr.reshape(-1, 1).shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

# 2 转置

## tensor.t() tensor是一个二维数据,如果不为二维就出错

In [25]:
arr3 = torch.randn(2, 3)
arr3

tensor([[ 0.7960,  0.7039, -0.7571],
        [-0.3944, -1.4380,  0.5308]])

In [26]:
arr3.t()

tensor([[ 0.7960, -0.3944],
        [ 0.7039, -1.4380],
        [-0.7571,  0.5308]])

In [27]:
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [28]:
# 高维数据不能用 t()
arr1.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

## tensor.transpose(dim1, dim2) 交换两个维度

In [32]:
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [33]:
arr1.transpose(1, 2)

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

## tensor.swapaxes(dim1, dim2) 交换两个维度

In [34]:
arr1.swapaxes(1, 2)

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

## tensor.permute(维度顺序) 改变维度顺序

In [35]:
arr1.permute(1, 2, 0)

tensor([[[ 1.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]]])

# 3 tensor.squeeze/unsqueeze(维度) 压缩,扩展维度

torch.squeeze(tensor)就是将tensor中所有为1的维度删掉。不为1的维度没有影响。默认删除所有维度为1的维度

tensor.squeeze(N)就是去掉a中指定的n维数为1的维度,**如果这个维度不为1则没影响**。

numpy和tf中是squeeze, expand_dim

In [36]:
arr4 = torch.randn(1, 2, 1, 3)
arr4

tensor([[[[ 1.4622, -0.0071, -1.1201]],

         [[-0.0754, -0.0507, -0.4371]]]])

In [37]:
arr4.squeeze()

tensor([[ 1.4622, -0.0071, -1.1201],
        [-0.0754, -0.0507, -0.4371]])

In [38]:
torch.squeeze(arr4)

tensor([[ 1.4622, -0.0071, -1.1201],
        [-0.0754, -0.0507, -0.4371]])

In [39]:
arr4.squeeze().dim()

2

In [40]:
arr4.squeeze(2)

tensor([[[ 1.4622, -0.0071, -1.1201],
         [-0.0754, -0.0507, -0.4371]]])

In [41]:
torch.squeeze(arr4, 2)

tensor([[[ 1.4622, -0.0071, -1.1201],
         [-0.0754, -0.0507, -0.4371]]])

In [42]:
arr4.squeeze(2).dim()

3

In [43]:
arr5 = torch.randn(2, 3)
arr5

tensor([[-0.3884,  2.3277,  1.4038],
        [-1.0415, -0.1831,  0.2636]])

In [44]:
arr5.unsqueeze(0)

tensor([[[-0.3884,  2.3277,  1.4038],
         [-1.0415, -0.1831,  0.2636]]])

In [45]:
arr5.unsqueeze(2)

tensor([[[-0.3884],
         [ 2.3277],
         [ 1.4038]],

        [[-1.0415],
         [-0.1831],
         [ 0.2636]]])

# 4 tensor.expand/repeat() 扩展/重复维度
**expand不会主动复制数据,repeat会真的复制数据(更慢)**

## tensor.expand(new_dims) 维度必须一致,原来维度为1可以扩展,原来维度不为1就不能扩展

new_dims 中的 -1 代表原来的值

### epxand 扩展原本为1的维度

In [46]:
arr6 = torch.rand(1, 3)
arr6

tensor([[0.6678, 0.3883, 0.9919]])

In [47]:
arr6.expand(2, 3)

tensor([[0.6678, 0.3883, 0.9919],
        [0.6678, 0.3883, 0.9919]])

In [48]:
arr6.expand(2, -1)

tensor([[0.6678, 0.3883, 0.9919],
        [0.6678, 0.3883, 0.9919]])

In [49]:
# 这样不行,要扩展的维度必须为1
arr6.expand(1, 6)

RuntimeError: The expanded size of the tensor (6) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [1, 6].  Tensor sizes: [1, 3]

### expand新增维度

In [50]:
arr7 = torch.ones(2, 3)
arr7

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [51]:
# 在第0维度复制4份
arr7.expand(4, 2, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [52]:
# 在第0维度复制4份
arr7.expand(4, -1, -1)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

## tensor.repeat/tile(每个维度复制次数)

In [53]:
arr8 = torch.rand(1, 2, 3)
arr8

tensor([[[0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173]]])

In [54]:
arr8.repeat(2, 1, 1)

tensor([[[0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173]],

        [[0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173]]])

In [55]:
arr8.repeat(2, 2, 2)

tensor([[[0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173],
         [0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173]],

        [[0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173],
         [0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173]]])

In [56]:
arr8.tile(2, 2, 2)

tensor([[[0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173],
         [0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173]],

        [[0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173],
         [0.1440, 0.7815, 0.3129, 0.1440, 0.7815, 0.3129],
         [0.7645, 0.6657, 0.6173, 0.7645, 0.6657, 0.6173]]])

In [57]:
arr8.repeat(2, 2, 2) == arr8.tile(2, 2, 2)

tensor([[[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]],

        [[True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True],
         [True, True, True, True, True, True]]])

### 重复次数必须为正数,不能用-1代表默认

In [58]:
arr8.repeat(2, -1, -1)

RuntimeError: Trying to create tensor with negative dimension -2: [2, -2, -3]