In [1]:
import torch

# 1 view/reshape(new_shape) 改变形状

形状改变: `tensor.view() or reshape()` 类似numpy中的reshape,是一种浅拷贝

1. view只能对连续内存的数据转换维度(浅拷贝)

    view是数据的一个别称或引用,通过该别称或引用亦便可访问、操作原有数据,但原有数据不会产生拷贝.如果我们对视图进行修改,它会影响到原始数据,物理内存在同一位置,这样避免了重新创建张量的高内存开销.

2. contiguous()会开辟新的内存空间

3. reshape()可以对不连续内存数据进行处理

    reshape可以开辟新的内存空间

    tensor内存连续, **a.reshape()** 返回的结果与 **a.view()** 相同,

    tensor内存不连续, **a.reshape()** 返回的结果与 **a.view().contiguous()** 相同.

In [2]:
arr = torch.arange(1, 13.)
arr

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [3]:
arr.view(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [4]:
arr.reshape(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [5]:
arr1 = arr.view(2, 3, 2)
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

## 经过转置之后的数据不连续,没法使用 view() 函数,要使用 contiguous().view() 或者使用 reshape()

In [6]:
arr2 = arr1.transpose(1, 2)
arr2

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

In [7]:
# 报错
arr2.view(2, 6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
# 必须使用连续区域
arr2.contiguous().view(2, 6)

tensor([[ 1.,  3.,  5.,  2.,  4.,  6.],
        [ 7.,  9., 11.,  8., 10., 12.]])

In [ ]:
arr2.reshape(2, 6)

tensor([[ 1.,  3.,  5.,  2.,  4.,  6.],
        [ 7.,  9., 11.,  8., 10., 12.]])

## view(-1, 1) 和 reshape(-1, 1) 将行向量调整为列向量

In [ ]:
arr

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
arr.view(-1, 1), arr.view(-1, 1).shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [8]:
arr.reshape(-1, 1), arr.reshape(-1, 1).shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

# 2 转置

## t() tensor是一个二维数据,如果不为二维就出错

In [9]:
arr3 = torch.randn(2, 3)
arr3

tensor([[-0.2272,  1.4380, -0.8331],
        [-1.3422, -0.2830, -0.7469]])

In [10]:
arr3.t()

tensor([[-0.2272, -1.3422],
        [ 1.4380, -0.2830],
        [-0.8331, -0.7469]])

In [11]:
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [12]:
# 高维数据不能用 t()
arr1.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

## transpose(dim1, dim2) 交换两个维度

In [13]:
arr1

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [14]:
arr1.transpose(1, 2)

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

## swapaxes(dim1, dim2) 交换两个维度

In [15]:
arr1.swapaxes(1, 2)

tensor([[[ 1.,  3.,  5.],
         [ 2.,  4.,  6.]],

        [[ 7.,  9., 11.],
         [ 8., 10., 12.]]])

## permute(维度顺序) 改变维度顺序

In [16]:
arr1.permute(1, 2, 0)

tensor([[[ 1.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]]])

# 3 squeeze/unsqueeze(维度) 压缩,扩展维度

torch.squeeze(tensor)就是将tensor中所有为1的维度删掉。不为1的维度没有影响。默认删除所有维度为1的维度

tensor.squeeze(N)就是去掉a中指定的n维数为1的维度,**如果这个维度不为1则没影响**。

numpy和tf中是squeeze, expand_dim

In [81]:
arr4 = torch.arange(6).reshape(1, 2, 1, 3)
arr4.shape

torch.Size([1, 2, 1, 3])

In [82]:
arr4.squeeze().shape

torch.Size([2, 3])

In [84]:
arr4.squeeze(2).shape

torch.Size([1, 2, 3])

In [88]:
arr5 = torch.arange(6).reshape(2, 3)
arr5.shape

torch.Size([2, 3])

In [89]:
arr5.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [92]:
# 可以使用 None 作为 unsqueeze 新的维度
arr5[None, :, :].shape

torch.Size([1, 2, 3])

In [93]:
arr5.unsqueeze(1).shape

torch.Size([2, 1, 3])

In [94]:
# 可以使用 None 作为 unsqueeze 新的维度
arr5[:, None, :].shape

torch.Size([2, 1, 3])

In [ ]:
arr5.unsqueeze(2).shape

torch.Size([2, 3, 1])

In [95]:
# 可以使用 None 作为 unsqueeze 新的维度
arr5[:, :, None].shape

torch.Size([2, 3, 1])

# 4 扩展/重复维度
**expand不会主动复制数据,repeat会真的复制数据(更慢)**

## expand(new_dims) 维度必须一致,原来维度为1可以扩展,原来维度不为1就不能扩展

new_dims 中的 -1 代表原来的值

### epxand 扩展原本为1的维度

In [121]:
arr6 = torch.arange(3).reshape(1, 3)
arr6

tensor([[0, 1, 2]])

In [122]:
arr6.expand(2, 3)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [123]:
arr6.expand(2, -1)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [124]:
# 这样不行,要扩展的维度必须为1
arr6.expand(1, 6)

RuntimeError: The expanded size of the tensor (6) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [1, 6].  Tensor sizes: [1, 3]

### expand新增维度

In [125]:
arr7 = torch.arange(6).reshape(2, 3)
arr7

tensor([[0, 1, 2],
        [3, 4, 5]])

In [126]:
# 在第0维度复制3份
arr7.expand(2, 2, 3)

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

In [127]:
# 在第0维度复制3份
arr7.expand(2, -1, -1)

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

## repeat/tile(每个维度复制次数) 重复整个序列

repeat() behaves differently from numpy.repeat, but is more similar to numpy.tile. For the operator similar to numpy.repeat, see torch.repeat_interleave().

In [109]:
arr8 = torch.arange(6).reshape(1, 2, 3)
arr8

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [110]:
arr8.repeat(2, 1, 1)

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

In [112]:
arr8.tile(2, 1, 1)

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

In [113]:
torch.all(arr8.repeat(2, 1, 1) == arr8.tile(2, 1, 1))

tensor(True)

### 重复次数必须为正数,不能用-1代表默认

In [114]:
arr8.repeat(2, -1, -1)

RuntimeError: Trying to create tensor with negative dimension -2: [2, -2, -3]

## repeat_interleave(repeats=重复次数, dim=指定维度) 相邻重复

repeat() behaves differently from numpy.repeat, but is more similar to numpy.tile. For the operator similar to numpy.repeat, see torch.repeat_interleave().

In [115]:
arr9 = torch.tensor([1, 2, 3])
arr9

tensor([1, 2, 3])

In [116]:
arr9.repeat_interleave(repeats=3, dim=0)
# 注意和repeat不同,这个的重复是紧邻的重复,repeat是重复整个序列

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [117]:
arr9.repeat(3)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [118]:
arr10 = torch.arange(6).reshape(1, 2, 3)
arr10

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [119]:
arr10.repeat_interleave(repeats=3, dim=1)

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [3, 4, 5],
         [3, 4, 5],
         [3, 4, 5]]])

In [120]:
arr10.repeat(1, 3, 1)

tensor([[[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]])