In [1]:
import torch
from torch import nn

# 二维数据

In [3]:
a = torch.arange(1, 25).view(6, 4)
a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [4]:
a.shape

torch.Size([6, 4])

## tensor.flatten(0) 全拼接到0维,默认为0
> tensor.flatten(0)是按照tensor的第0个维度拼接（按照行来拼接，纵向拼接）

In [10]:
a.flatten()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [11]:
a.flatten(0)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [12]:
a.flatten() == a.flatten(0)

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True])

In [13]:
torch.flatten(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [14]:
torch.flatten(a, 0)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

## nn.Flatten(0)

In [24]:
flatten = nn.Flatten(0)

In [25]:
flatten(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

## tensor.flatten(1) 拼接到0,1维
> tensor.flatten(1)是按照tensor的第1个维度拼接（按照列来拼接，横向拼接）

In [26]:
a.flatten(1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [27]:
torch.flatten(a, 1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

## nn.Flatten(1) 默认为1

In [36]:
flatten = nn.Flatten()

In [37]:
flatten(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [38]:
flatten = nn.Flatten(1)

In [39]:
flatten(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

# 三维数据

In [40]:
b = torch.arange(1, 25).view(2, 3, 4)
b

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [41]:
b.shape

torch.Size([2, 3, 4])

## torch.flatten(0) 全拼接到0维
> tensor.flatten(0)是按照tensor的第0个维度拼接（按照行来拼接，纵向拼接）

In [42]:
b.flatten(0)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [43]:
torch.flatten(b, 0)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

## nn.Flatten(0)

In [45]:
flatten = nn.Flatten(0)

In [46]:
flatten(b)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

## flatten(a, 1) 拼接到0,1维

> tensor.flatten(1)是按照tensor的第1个维度拼接（按照列来拼接，横向拼接）

In [44]:
b.flatten(1)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [17]:
torch.flatten(b, 1)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

## nn.Flatten(1) 默认为1

In [49]:
flatten = nn.Flatten(1)

In [53]:
flatten(b)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

## tensor.flatten(2) 拼接到0,1,2维

> tensor.flatten(2)是按照tensor的第2个维度拼接（按照列来拼接，横向拼接）

In [51]:
b.flatten(2)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [52]:
torch.flatten(b, 2)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

## nn.Flatten(2)

In [54]:
flatten = nn.Flatten(2)

In [55]:
flatten(b)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

## tensor.flatten(start, end)，将从start到end之间的所有维度值乘起来，其他的维度保持不变。

### tensor.flatten(0, 1) 0,1两个维度相乘,剩余两个维度

In [56]:
b.flatten(0, 1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [57]:
torch.flatten(b, 0, 1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

### nn.Flatten(0, 1)

In [58]:
flatten = nn.Flatten(0, 1)

In [59]:
flatten(b)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

### tensor.flatten(0, 2) 0,1,2三个维度相乘,剩余1个维度

In [24]:
b.flatten(0, 2)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [23]:
torch.flatten(b, 0, 2)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

### nn.Flatten(0, 2)

In [60]:
flatten = nn.Flatten(0, 2)

In [61]:
flatten(b)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

# view flatten

In [28]:
x = torch.rand(2, 3, 10, 10)

x = x.view(x.size(0), -1)
print(x.size())  # [2, 300]
x = torch.flatten(x, 1)
print(x.size())  # [2, 300]
x = x.flatten(1)
print(x.size())  # [2, 300]

torch.Size([2, 300])
torch.Size([2, 300])
torch.Size([2, 300])
