In [1]:
import torch

In [3]:
x = torch.arange(10).reshape(2, 5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# flip 倒序数据,需要指定维度

注意torch.flip是反序地复制一份新的数据，这一点与NumPy不同，NumPy是返回一个view，因而使用torch.flip耗时更久

In [9]:
# 倒序0维度
torch.flip(x, dims=[0])

tensor([[5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]])

In [6]:
# 倒序0维度
x.flip(dims=[0])

tensor([[5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]])

In [ ]:
# 倒序1维度
torch.flip(x, dims=[1])

tensor([[4, 3, 2, 1, 0],
        [9, 8, 7, 6, 5]])

In [7]:
# 倒序1维度
x.flip(dims=[1])

tensor([[4, 3, 2, 1, 0],
        [9, 8, 7, 6, 5]])

In [11]:
# 倒序0,1维度
torch.flip(x, dims=[0, 1])

tensor([[9, 8, 7, 6, 5],
        [4, 3, 2, 1, 0]])

In [12]:
# 倒序0,1维度
x.flip(dims=[0, 1])

tensor([[9, 8, 7, 6, 5],
        [4, 3, 2, 1, 0]])