In [1]:
import torch

# torch.where(cond, a, b) cond成立,选择a的相应位置的值,否则选择b的位置的值

In [2]:
cond = torch.rand([2, 2])
cond

tensor([[0.0795, 0.9303],
        [0.7779, 0.4546]])

In [20]:
#           cond大于0.5的位置选择1,否则选择0
torch.where(cond > 0.5, 1.0, 0.0)

tensor([[0., 1.],
        [1., 0.]])

In [21]:
a = torch.arange(1, 5).reshape(2, 2)
b = torch.arange(5, 9).reshape(2, 2)
a, b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [22]:
#           cond大于0.5的位置选择cond,否则选择b
torch.where(cond > 0.5, cond, a)

tensor([[1.0000, 0.9303],
        [0.7779, 4.0000]])

# torch.gather(a, index=[索引位置], dim=维度) 从dim维度从a中选择index的数据

In [50]:
x = torch.arange(1, 7).reshape(2, 3)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
#               从dim=1找下标为0的是1
torch.gather(x, dim=1, index=torch.tensor([[0]]))

tensor([[1]])

In [52]:
#               从dim=1找下标为0的是1,2个都是
torch.gather(x, dim=1, index=torch.tensor([[0, 0]]))

tensor([[1, 1]])

In [53]:
#               从dim=1找下标为0的是1
torch.gather(x, dim=1, index=torch.tensor([[0]]))

tensor([[1]])

In [54]:
#               第一维度的[0]从dim=1找下标为0的是1,第2维度的[0]是在dim=1中的index=1的值,为4
torch.gather(x, dim=1, index=torch.tensor([[0], [0]]))

tensor([[1],
        [4]])

In [55]:
#               第一维度的[0, 0]从dim=1找下标为0的是1,第2维度的[0, 1]是在dim=1中的index=1的值,为4
torch.gather(x, dim=1, index=torch.tensor([[0, 0], [0, 1]]))

tensor([[1, 1],
        [4, 5]])