In [1]:
import torch

# torch.roll(input, shifts, dims=None)/tensor.roll(input, shifts, dims=None) 滚动数据

In [16]:
x = torch.arange(1, 9)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x.roll(shifts=1)

tensor([8, 1, 2, 3, 4, 5, 6, 7])

In [18]:
x.roll(shifts=2)

tensor([7, 8, 1, 2, 3, 4, 5, 6])

In [19]:
x.roll(shifts=-1)

tensor([2, 3, 4, 5, 6, 7, 8, 1])

In [20]:
x = x.view(4, 2)
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [21]:
x.roll(shifts=1)

tensor([[8, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [22]:
x.roll(shifts=2)

tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])

In [23]:
x.roll(shifts=1, dims=0)

tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])

In [24]:
x.roll(shifts=1, dims=1)

tensor([[2, 1],
        [4, 3],
        [6, 5],
        [8, 7]])

In [25]:
x.roll(shifts=(2, 1), dims=(0, 1))

tensor([[6, 5],
        [8, 7],
        [2, 1],
        [4, 3]])