In [1]:
import torch

# torch.where(cond, a, b) cond成立,选择a的相应位置的值,否则选择b的位置的值

In [14]:
torch.manual_seed(0)
cond = torch.rand([2, 2])
cond

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
#           cond大于0.5的位置选择1,否则选择0
torch.where(cond > 0.5, 1.0, 0.0)

tensor([[0., 1.],
        [0., 0.]])

In [16]:
a = torch.arange(1, 5).reshape(2, 2)
b = torch.arange(5, 9).reshape(2, 2)
a, b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [17]:
#           cond大于0.5的位置选择a,否则选择b
torch.where(cond > 0.5, a, b)

tensor([[5, 2],
        [7, 8]])

# torch.gather(a, index=[索引位置], dim=维度) 从dim维度从a中选择index的数据

In [18]:
x = torch.arange(1, 7).reshape(2, 3)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
#               从dim=1找下标为0的是1
torch.gather(x, dim=1, index=torch.tensor([[0]]))

tensor([[1]])

In [27]:
#               从dim=1找下标为0的是1,2个都是
torch.gather(x, dim=1, index=torch.tensor([[0, 0]]))

tensor([[1, 1]])

In [28]:
#               从dim=1找下标为0的是1
torch.gather(x, dim=1, index=torch.tensor([[0, 1]]))

tensor([[1, 2]])

In [29]:
#               第一维度的[0]从dim=1找下标为0的是1,第2维度的[0]是在dim=1中的index=1的值,为4
torch.gather(x, dim=1, index=torch.tensor([[0], [0]]))

tensor([[1],
        [4]])

In [30]:
#               第一维度的[0, 0]从dim=1找下标为0的是1,第2维度的[0, 1]是在dim=1中的index=1的值,为4
torch.gather(x, dim=1, index=torch.tensor([[0, 0], [0, 1]]))

tensor([[1, 1],
        [4, 5]])

# torch.multinomial(input, num_samples,replacement=False, out=None)

- input: 输入张量或矩阵(里面数据不能有小于0的)
- num_samples: 每行的取值次数，该值不能大于每一行的元素数，否则会报错。
- replacement: 布尔值表示取样时有无放回，True是有放回，False无放回。
- 函数作用: 对input中的每一行做n_samples次取值，每一次取值时的输出张量是input当前行对应元素的下标。
- 取样原则: input可以看成一个权重张量，每一个元素的值代表其在该行中的权重。如果有元素为0，那么在其他不为0的元素被取完之前，该元素不会被取到。
- out: 取到的数据的下标

In [50]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float)
weights

tensor([ 0., 10.,  3.,  0.])

In [51]:
torch.multinomial(weights, 2)

tensor([1, 2])

In [52]:
torch.multinomial(weights, 4)

tensor([1, 2, 0, 3])

In [53]:
# 重复获取数据
torch.multinomial(weights, 4, replacement=True)

tensor([1, 1, 1, 1])

In [56]:
weights = torch.tensor([[0, 10, 3, 0], [1, 0, 0, 4]], dtype=torch.float)
weights

tensor([[ 0., 10.,  3.,  0.],
        [ 1.,  0.,  0.,  4.]])

In [57]:
torch.multinomial(weights, 2)

tensor([[2, 1],
        [3, 0]])

In [58]:
torch.multinomial(weights, 4)

tensor([[1, 2, 0, 3],
        [3, 0, 1, 2]])

In [59]:
# 重复获取数据
torch.multinomial(weights, 4, replacement=True)

tensor([[2, 1, 2, 1],
        [3, 3, 3, 3]])