In [1]:
import torch

# torch.repeat_interleave(1dTensor)
> 将tensor转换为重复 0 1 2... 多少次

In [2]:
torch.repeat_interleave(torch.tensor([2]))

tensor([0, 0])

In [3]:
torch.repeat_interleave(torch.tensor([2, 3]))

tensor([0, 0, 1, 1, 1])

In [4]:
torch.repeat_interleave(torch.tensor([2, 3, 4]))

tensor([0, 0, 1, 1, 1, 2, 2, 2, 2])

# torch.repeat_interleave(inputTensor, repeatsTensor)
> 将 inputTensor 每个都重复 repeatsTensor 次

In [9]:
torch.repeat_interleave(torch.tensor([2, 3, 4]), torch.tensor(2))

tensor([2, 2, 3, 3, 4, 4])

In [10]:
torch.repeat_interleave(torch.tensor([2, 3]), torch.tensor(3))

tensor([2, 2, 2, 3, 3, 3])