https://arxiv.org/abs/1609.05158

In [23]:
import torch
from torch import nn
import torch.nn.functional as F

In [24]:
x = torch.ones(1, 1, 5, 5)
x = torch.cat([x * i for i in range(1, 5)], dim=1)
print(x.shape)
x

torch.Size([1, 4, 5, 5])


tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.]],

         [[4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.]]]])

# PixelShuffle 上采样,通道减少,数据量不变

Shape:
- Input: `(*, C_{in}, H_{in}, W_{in})`, where * is zero or more batch dimensions
- Output: `(*, C_{out}, H_{out}, W_{out})`, where

$$
C_{out} = C_{in} \div \text{upscale\_factor}^2 \\

H_{out} = H_{in} \times \text{upscale\_factor} \\

W_{out} = W_{in} \times \text{upscale\_factor}
$$

![PixelShuffle](PixelShuffle.png)


In [25]:
pixel_shuffle = nn.PixelShuffle(upscale_factor=2)
y1 = pixel_shuffle(x)
print(y1.shape)
y1

torch.Size([1, 1, 10, 10])


tensor([[[[1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.]]]])

In [26]:
y2 = F.pixel_shuffle(x, upscale_factor=2)
print(y2.shape)
y2

torch.Size([1, 1, 10, 10])


tensor([[[[1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.],
          [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.],
          [3., 4., 3., 4., 3., 4., 3., 4., 3., 4.]]]])

In [27]:
torch.all(y1 == y2)

tensor(True)

# PixelUnshuffle 下采样,通道增多,数据量不变

Shape:
- Input: `(*, C_{in}, H_{in}, W_{in})`, where * is zero or more batch dimensions
- Output: `(*, C_{out}, H_{out}, W_{out})`, where

$$
C_{out} = C_{in} \times \text{downscale\_factor}^2 \\

H_{out} = H_{in} \div \text{downscale\_factor} \\

W_{out} = W_{in} \div \text{downscale\_factor}
$$

In [28]:
pixel_unshuffle = nn.PixelUnshuffle(downscale_factor=2)
x1 = pixel_unshuffle(y1)
print(x1.shape)
x1

torch.Size([1, 4, 5, 5])


tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.]],

         [[4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.]]]])

In [29]:
x2 = F.pixel_unshuffle(y2, downscale_factor=2)
print(x2.shape)
x2

torch.Size([1, 4, 5, 5])


tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2.]],

         [[3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.]],

         [[4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.],
          [4., 4., 4., 4., 4.]]]])

In [30]:
torch.all(x == x1), torch.all(x1 == x2)

(tensor(True), tensor(True))