In [9]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
a = torch.ones(1)
a

tensor([1.])

# torch.nn.functional.pad(tensor, [左, 右, 上, 下])

In [5]:
F.pad(a, [1, 1, 1, 1])

RuntimeError: Padding length too large

In [6]:
b = torch.ones(1, 1)
b

tensor([[1.]])

In [7]:
F.pad(b, [1, 1, 1, 1])

tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])

In [8]:
F.pad(b, [1, 2, 3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# nn.ZeroPad2d(size) size: int 代表上下左右相同 size: list[int] 代表 左, 右, 上, 下

In [10]:
pad1 = nn.ZeroPad2d(1)

In [11]:
pad1(b)

tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])

In [14]:
pad2 = nn.ZeroPad2d((1, 2))

In [15]:
pad2(b)

tensor([[0., 1., 0., 0.]])

In [16]:
pad3 = nn.ZeroPad2d((1, 2, 3, 4))

In [17]:
pad3(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])