In [1]:
import torch
from torch import nn, Tensor
from torch.nn import functional as F

# 平均绝对误差(mean absolute error, MAE / L1Loss)

In [2]:
def l1_loss(input: Tensor, target: Tensor, reduction="mean") -> Tensor:
    """l1 loss
    input and target shape should be same.

    Args:
        input (Tensor):  predict value
        target (Tensor): target value
        reduction (str, optional): mean' | 'sum' | 'none'. Defaults to 'mean'.

    Returns:
        Tensor: mae result
    """
    if target.size() != input.size():
        warnings.warn(
            "Using a target size ({}) that is different to the input size ({}). "
            "This will likely lead to incorrect results due to broadcasting. "
            "Please ensure they have the same size.".format(
                target.size(), input.size()
            ),
            stacklevel=2,
        )

    result: Tensor = torch.abs(input - target)
    if reduction == "mean":
        return result.mean()
    elif reduction == "sum":
        return result.sum()
    elif reduction == "none":
        return result

## 一维数据

In [3]:
y_true = torch.tensor([1, 0, 1, 0])

In [7]:
y_pred = torch.tensor([0.8, 0.1, 0.7, 0.3])

In [9]:
print(nn.L1Loss(reduction="mean")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="mean"))
print(l1_loss(y_pred, y_true, reduction="mean"))

tensor(0.2250)
tensor(0.2250)
tensor(0.2250)


In [10]:
print(nn.L1Loss(reduction="sum")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="sum"))
print(l1_loss(y_pred, y_true, reduction="sum"))

tensor(0.9000)
tensor(0.9000)
tensor(0.9000)


In [11]:
print(nn.L1Loss(reduction="none")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="none"))
print(l1_loss(y_pred, y_true, reduction="none"))

tensor([0.2000, 0.1000, 0.3000, 0.3000])
tensor([0.2000, 0.1000, 0.3000, 0.3000])
tensor([0.2000, 0.1000, 0.3000, 0.3000])


## 二维数据

In [12]:
y_true = torch.tensor(
    [
        [1, 0, 1, 0],
        [1, 1, 0, 0],
    ]
)

In [13]:
y_pred = torch.tensor(
    [
        [0.8, 0.1, 0.7, 0.3],
        [0.9, 0.6, 0.5, 0.3],
    ]
)

In [14]:
print(nn.L1Loss(reduction="mean")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="mean"))
print(l1_loss(y_pred, y_true, reduction="mean"))

tensor(0.2750)
tensor(0.2750)
tensor(0.2750)


In [15]:
print(nn.L1Loss(reduction="sum")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="sum"))
print(l1_loss(y_pred, y_true, reduction="sum"))

tensor(2.2000)
tensor(2.2000)
tensor(2.2000)


In [16]:
print(nn.L1Loss(reduction="none")(y_pred, y_true))
print(F.l1_loss(y_pred, y_true, reduction="none"))
print(l1_loss(y_pred, y_true, reduction="none"))

tensor([[0.2000, 0.1000, 0.3000, 0.3000],
        [0.1000, 0.4000, 0.5000, 0.3000]])
tensor([[0.2000, 0.1000, 0.3000, 0.3000],
        [0.1000, 0.4000, 0.5000, 0.3000]])
tensor([[0.2000, 0.1000, 0.3000, 0.3000],
        [0.1000, 0.4000, 0.5000, 0.3000]])
