In [10]:
import torch
from torch import nn

# 最小绝对值误差（mean absolute error, MAE）

## 一维数据

In [11]:
y_true = torch.rand(10)
y_true

tensor([0.5635, 0.2605, 0.8293, 0.0146, 0.5081, 0.1522, 0.9936, 0.5834, 0.2480,
        0.5615])

In [12]:
y_pred = torch.rand(10)
y_pred

tensor([0.9356, 0.6484, 0.7063, 0.9359, 0.0968, 0.6317, 0.7915, 0.0608, 0.9633,
        0.1006])

In [13]:
nn.L1Loss()(y_pred, y_true)

tensor(0.4596)

In [14]:
# sum(abs(真实值 - 预测值)) / 总个数
((y_true - y_pred).abs()).sum() / torch.prod(torch.tensor(y_true.size()))

tensor(0.4596)

## 二维数据

In [15]:
y_true = torch.rand(10, 5)
y_true

tensor([[0.3305, 0.3757, 0.0903, 0.8515, 0.8375],
        [0.2171, 0.5290, 0.2119, 0.8710, 0.3386],
        [0.7337, 0.8908, 0.7560, 0.0135, 0.4066],
        [0.0304, 0.5049, 0.7096, 0.3600, 0.4529],
        [0.0449, 0.0559, 0.4816, 0.9240, 0.3635],
        [0.3908, 0.4755, 0.8265, 0.9238, 0.9763],
        [0.3093, 0.6626, 0.9850, 0.5102, 0.2061],
        [0.6262, 0.1254, 0.6180, 0.0844, 0.0966],
        [0.0694, 0.8144, 0.4231, 0.5592, 0.8238],
        [0.8905, 0.7507, 0.5588, 0.5601, 0.8387]])

In [16]:
y_pred = torch.rand(10, 5)
y_pred

tensor([[0.9306, 0.4865, 0.0335, 0.7739, 0.3703],
        [0.7065, 0.1232, 0.3815, 0.2387, 0.8665],
        [0.4223, 0.9684, 0.1057, 0.9231, 0.7359],
        [0.0178, 0.7434, 0.5201, 0.2527, 0.4815],
        [0.9386, 0.0496, 0.0075, 0.1403, 0.5788],
        [0.5486, 0.6024, 0.6130, 0.5723, 0.7911],
        [0.7947, 0.0894, 0.1410, 0.3751, 0.6397],
        [0.8139, 0.2453, 0.3342, 0.3090, 0.1318],
        [0.9364, 0.7862, 0.8966, 0.9451, 0.9333],
        [0.5337, 0.9385, 0.8610, 0.6759, 0.0011]])

In [17]:
nn.L1Loss()(y_pred, y_true)

tensor(0.3357)

In [18]:
# sum(abs(真实值 - 预测值)) / 总个数
((y_true - y_pred).abs()).sum() / torch.prod(torch.tensor(y_true.size()))

tensor(0.3357)