In [45]:
import torch
from torch import nn

# 均方误差（mean square error, MSE）

## 一维数据

In [46]:
y_true = torch.rand(10)
y_true

tensor([0.5242, 0.5859, 0.6143, 0.9404, 0.0913, 0.6553, 0.5622, 0.0624, 0.7742,
        0.8489])

In [47]:
y_pred = torch.rand(10)
y_pred

tensor([0.1736, 0.0681, 0.2156, 0.8476, 0.7101, 0.5407, 0.9110, 0.6713, 0.3426,
        0.4399])

In [48]:
nn.MSELoss()(y_pred, y_true)

tensor(0.1801)

In [49]:
# sum((真实值 - 预测值) ** 2) / 总个数
((y_true - y_pred) ** 2).sum() / torch.prod(torch.tensor(y_true.size()))

tensor(0.1801)

## 二维数据

In [50]:
y_true = torch.rand(10, 5)
y_true

tensor([[0.5824, 0.7589, 0.9238, 0.0078, 0.2258],
        [0.9996, 0.7851, 0.4015, 0.9300, 0.2434],
        [0.9700, 0.5983, 0.1241, 0.5141, 0.7230],
        [0.2492, 0.3589, 0.8106, 0.5675, 0.8832],
        [0.3851, 0.8063, 0.7408, 0.7614, 0.4266],
        [0.1152, 0.4980, 0.1477, 0.8273, 0.9455],
        [0.2234, 0.0029, 0.3884, 0.0728, 0.1651],
        [0.3163, 0.2643, 0.4146, 0.3754, 0.8883],
        [0.6791, 0.3652, 0.7507, 0.4466, 0.6994],
        [0.4758, 0.3309, 0.8015, 0.6827, 0.7556]])

In [51]:
y_pred = torch.rand(10, 5)
y_pred

tensor([[0.1378, 0.3853, 0.3126, 0.1454, 0.6894],
        [0.6401, 0.0133, 0.2043, 0.6745, 0.9196],
        [0.6915, 0.9245, 0.3396, 0.9031, 0.9868],
        [0.5437, 0.0672, 0.1702, 0.1977, 0.9976],
        [0.9853, 0.7265, 0.5694, 0.0245, 0.3997],
        [0.4978, 0.3890, 0.4293, 0.5943, 0.9765],
        [0.3212, 0.9763, 0.5978, 0.1405, 0.9924],
        [0.2151, 0.8128, 0.6701, 0.3359, 0.1010],
        [0.8237, 0.7603, 0.3371, 0.3632, 0.2906],
        [0.6051, 0.7338, 0.4187, 0.1415, 0.1700]])

In [52]:
nn.MSELoss()(y_pred, y_true)

tensor(0.1764)

In [53]:
# sum((真实值 - 预测值) ** 2) / 总个数
((y_true - y_pred) ** 2).sum() / torch.prod(torch.tensor(y_true.size()))

tensor(0.1764)